- slackclient/_slackrequest.py
When debugging an issue for a customer I realized that we send `ts` parameter on every call to the API, set to `time.time()`. Unfortunately some of our API methods (e.g. [chat.update](https://api.slack.com/methods/chat.update)) use a `ts` argument, so were impossible to call.
This pull request fixes that issue. But, I don't know all of the details of this code so I may have missed a reason for sending this argument? I couldn't find anything in commit history!
> Don't send current time as ts to every API call

- slackclient/_server.py
With the current implementation, a disconnected websocket is not
detected as *all* exceptions are silently swallowed, resulting in
`rtm_read()` returning an empty list forever without raising any
kind of exception.
This makes it impossible to detect that the websocket has been
disconnected and keeps client libraries reading forever while never
receiving data anymore.
With these changes, a `socket.error` (python 2) or `TimeoutError` (python 3)
will be thrown when the socket
gets disconnected (and other exceptions should bubble up as well) so
that users of this library know they must re-connect.
> Detect disconnected websocket connections

- slackclient/_server.py
42bfde0082f5c26bc94b94f62fcffcbcc14969b2 introduced a change that relied on an Exception class ([ssl.SSLWantReadError]()) present only in modern Python versions. This changes that to work exactly the same way, only in a way that works for older Python versions also.
Fixes #29.
> Re-introduce support for Python < 2.7.9

- setup.py
- slackclient/_slackrequest.py
This addresses a bug I was running into in python2 while my environment has the `six` and `future` packages installed.
Here's the stack trace I was getting prior to this fix.
Note that this PR adds a dependency on the `future` package.
```
File "/home/maxime_beauchemin/airflow/airflow/operators/slack_operator.py", line 50, in execute
sc.api_call(self.method, **self.params)
File "/home/maxime_beauchemin/code/python-slackclient/slackclient/_client.py", line 21, in api_call
return self.server.api_call(method, **kwargs)
File "/home/maxime_beauchemin/code/python-slackclient/slackclient/_server.py", line 133, in api_call
reply = self.api_requester.do(self.token, method, kwargs)
File "/home/maxime_beauchemin/code/python-slackclient/slackclient/_slackrequest.py", line 17, in do
return …
```
> Fixing urllib py2/3 compatibility

- slackclient/_client.py
A small change to handle "team_join" events in the same way "channel_created" and "im_created" events are handled, keeping the servers list of users updated.
> Add users to local cache in server when they join the team

- README.md
Replaced "channnels" with "channels". This is admittedly a low hanging fruit, but could possibly foil someone at the eleventh hour of a hackathon.
> Corrected incorrect code example in readme

- slackclient/_server.py
Occasionally, there will be duplicate channels in the `client.server.channels` instance. User lists will also be duplicated when this happens.
This is likely caused by reconnection issues or resent messages from the Slack API, but the end result is that message sending will crash when sending to channels that are duplicated:
File "/root/botty-bot-bot-bot/src/bot.py", line 79, in say
self.client.rtm_send_message(channel_id, sendable_text)
File "/usr/local/lib/python3.4/dist-packages/slackclient/_client.py", line 39, in rtm_send_message
return self.server.channels.find(channel).send_message(message)
AttributeError: 'list' object has no attribute 'send_message'
This patch fixes the issue by preventing duplicated channels from occurring.
> Fix duplicate channels and users issue.

- slackclient/_client.py
This fixes the issue that newly joined/created private groups and multi-person direct messages are not recognized until the bot is restarted as documented in #55 and slackhq/python-rtmbot#24
> Adding support for private groups and multi-person direct messages

- _pytest/conftest.py
- _pytest/test_channel.py
- _pytest/test_server.py
- _pytest/test_slackclient.py
- slackclient/_channel.py
- slackclient/_client.py
- slackclient/_im.py
- slackclient/_server.py
- slackclient/_slackrequest.py
- slackclient/_user.py
- slackclient/_util.py
This PR resolves a number of PEP8 errors and makes a few miscellaneous improvements. 
**Note**: No functionality was added or removed, but there is a bugfix to make default arguments immutable.
- Fixes PEP8 whitespacing
- Changes variables names that shadow outer scope
- Adds an explicit return value to `_util.find`
- Remove unused imports
- Make `SlackRequest.do method static`
- Define instance variable `ws_url` in `Server.__init__`
> [CLEANUP] Resolve PEP8 errors and misc improvements

- README.md
Fixes #62, correcting readme to indicate args to the api_call are passed as kwargs and not a dict.
> better explain args in readme

- slackclient/_client.py
Fix for #73. Also closes #47 by way of solving the same problem that #70 does. I'm closing #70 myself.
> api_call should update server state in rtm mode

- slackclient/_channel.py
- tests/test_channel.py
Merging PR from pbanaray and adding tests to this method.
> Fix bug in __eq__ comparison on Channel class

- README.md
- requirements-dev.txt
- requirements.txt
- setup.py
- slackclient/_slackrequest.py
- tests/test_slackrequest.py
> The optional attachments argument should contain a JSON-encoded array of attachments.
>
> https://api.slack.com/methods/chat.postMessage
This enables simpler calls like this:
```python
sc.api_call('chat.postMessage', {'attachments': [{'title': 'hello'}]})
sc.api_call('chat.postMessage', {'attachments': json.dumps([{'title': 'hello'}]}))
```
> Add support for nested structure, e.g. attachments

- slackclient/_channel.py
- slackclient/_im.py
- slackclient/_server.py
- slackclient/_user.py
- tests/test_channel.py
- tests/test_server.py
In python 3, objects with `__eq__` methods need `__hash__` methods. Thus, here we write `__hash__` methods for the objects we have that were previously not hashable.
> make objects python3 compatible

- slackclient/_slackrequest.py
- tests/test_slackrequest.py
> e.g. Fix bug for requests with a 'file' argument. The current code assumes 'file' is always a file's content (upload), whereas there are many requests that take a fileID with the argument name 'file'.
> N/A (that I have found)
> e.g. Test files.info in addition to the files.upload test that already exists.
> Fix bug: requests with a 'file' argument work now

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
This PR fixes the link in the issue and PR templates. Before they were based on relative urls but this would cause 404s when clicked in certain contexts. Moving to absolute urls the templates resolves this issue.
Fixes #121 
Manual verification
> Fix contributing guideline link

- docs/index.rst
> Included instructions on installing virtualenv, creating a new env and starting the env before building the docs to be more explicit.
> Added a link to the slack contribution guide in the contributions section of the documentation.
> None
> No tests needed
> Add contribution guide and virtualenv set up in documentation

- docs/index.rst
Fix indentation for `else` block in RTM example in documentation
> Fix indentation for `else` block in RTM example

- tox.ini
Moved coveralls call into after_success in tox config
Fixes travis/coveralls failure
* ✅  I've read and understood the [Contributing guidelines](https://github.com/slackapi/python-slackclient/blob/master/.github/CONTRIBUTING.md) and have done my best effort to follow them.
* ✅ I've read and agree to the [Code of Conduct](https://github.com/slackapi/python-slackclient/blob/master/CODE_OF_CONDUCT.md).
* ✅ I've been mindful about doing atomic commits, adding documentation to my changes, not refactoring too much.
* ✅ I've a descriptive title and added any useful information for the reviewer. Where appropriate, I've attached a screenshot and/or screencast (gif preferably).
* ◻️  I've written tests to cover the new code and functionality included in this PR.
* ✅ I've read, agree to, and signed …
> Moved coveralls call into after_success in tox config

- slackclient/_server.py
- slackclient/_util.py
- tests/test_server.py
On some large teams with thousands of users, the `parse_user_data` method in the _server.py was blocking the websocket connection for so long that the websocket URL was expiring before the client attempted to connect to it. I've tested this change on an account with tens of thousands of users, and it doesn't timeout.
Fixes #127 
Tests didn't need updating, as the result signature was the same, but I added some additional testing to increase coverage.
* ✅ I've read and understood the Contributing guidelines.
* ✅ I've read and agree to the Code of Conduct.
* ✅ I've been mindful about doing atomic commits.
* ✅ I've a descriptive title and added any useful information for the reviewer..
* ✅ I've written tests to cover the new code and functionality included in this PR.
* ✅ I've read, agree …
> Updated RTM user parsing to use a dict instead of a list.

- docs-src/changelog.rst
- setup.py
> Updated changelog to acknowledge 1.0.2 release notes and add 1.0.3 notes
* ✅  I've read and understood the Contributing guidelines
* ✅  I've read and agree to the Code of Conduct
* ✅ I've been mindful about doing atomic commits, adding documentation to my changes, not refactoring too much.
* ✅  I've a descriptive title and added any useful information for the reviewer
* ✅ I've written tests to cover the new code and functionality included in this PR.
* ✅ I've read, agree to, and signed the Contributor License Agreement (CLA
> Updated changelog for 1.0.2 and 1.0.3

- slackclient/_util.py
- tests/test_server.py
> Release 1.0.3 broke the ability to search for user by id. This restores that functionality.
> Fixes #151
> Added tests for searching for user by id
✅  I've read and understood the Contributing guidelines
✅  I've read and agree to the Code of Conduct
✅  I've been mindful about doing atomic commits, adding documentation to my changes, not refactoring too much.
✅  I've a descriptive title and added any useful information for the reviewer.
✅  I've written tests to cover the new code and functionality included in this PR.
✅  I've read, agree to, and signed the Contributor License Agreement
> Fixed the ability to search for a user by ID

- slackclient/_client.py
- slackclient/_server.py
- slackclient/_slackrequest.py
From the requests [documentation](http://docs.python-requests.org/en/master/user/quickstart/#timeouts) regarding the timeout parameter:
> Nearly all production code should use this parameter in nearly all requests. Failure to do so can cause your program to hang indefinitely
Previously there was no timeout on the Api calls, and you could end up hanging indefinitely. This PR adds the option to add timeout, but defaults to keeping the existing behaviour.
There are no tests. Suggestions as to how to test are welcomed...
> Added timeout to api calls.

- setup.py
- slackclient/_client.py
- slackclient/_server.py
- slackclient/_slackrequest.py
- slackclient/version.py
- tests/test_slackrequest.py
> Adds `user-agent` headers to Web API requests.
> Added tests.
✅ I've read and understood the [Contributing guidelines](https://github.com/slackapi/python-slackclient/blob/master/.github/CONTRIBUTING.md) and have done my best effort to follow them.
✅ I've read and agree to the [Code of Conduct](https://github.com/slackapi/python-slackclient/blob/master/CODE_OF_CONDUCT.md).
✅ I've been mindful about doing atomic commits, adding documentation to my changes, not refactoring too much.
✅ I've a descriptive title and added any useful information for the reviewer. Where appropriate, I've attached a screenshot and/or screencast (gif preferably).
✅ I've written tests to cover the new code and functionality included in this PR.
✅ I've read, agree to, and signed the [Contributor License Agreement …
> Add user-agent headers

- slackclient/_server.py
- slackclient/_util.py
> Since it's more common to search for users by ID, index the dictionary by user ID instead of name.
> Also fixed a typo where `user_id` was `channel_id`
> No additional tests needed
✅ I've read and understood the [Contributing guidelines](https://github.com/slackapi/python-slackclient/blob/master/.github/CONTRIBUTING.md) and have done my best effort to follow them.
✅ I've read and agree to the [Code of Conduct](https://github.com/slackapi/python-slackclient/blob/master/CODE_OF_CONDUCT.md).
✅ I've been mindful about doing atomic commits, adding documentation to my changes, not refactoring too much.
✅ I've a descriptive title and added any useful information for the reviewer. Where appropriate, I've attached a screenshot and/or screencast (gif preferably).
✅ I've written tests to cover the …
> Index users by ID instead of name

- docs-src/real_time_messaging.rst
- slackclient/_channel.py
- slackclient/_client.py
- tests/test_channel.py
This PR adds two keyword arguments to `slackclient._channel.Channel.send_message`: `thread` and `reply_broadcast`. These allow a message sent using this method to be marked as a reply to a thread, and optionally to be posted back to the channel.
This makes it easier to meet Slack's Best Practices for bots (https://api.slack.com/docs/message-threading#best_practices) which states that they should reply to threaded messages in the same thread.
It also fixes the test for send_message by monkeypatching the server attribute, and adds an extra test for the new functionality.
None
> e.g. Add tests around whatsit production.
> Allow Channel.send_message to reply to a thread

- README.rst
Fix rst warning in README. This may be why the pypi homepage for this package is unstyled, so the PKG-INFO should be updated when this is merged.
Confirm warning:
```<div class="system-message">
<p class="system-message-title">System Message: WARNING/2 (<tt class="docutils">README.rst</tt>, line 95)</p>
<p>Title underline too short.</p>
<pre class="literal-block">
Replying to messages and creating threads
********************
</pre>
</div>
```
is no longer present when the README is rendered with rst2html.
> Extent too short Title underline in README

- slackclient/server.py
We have thousands and the WS URL was invalid by the time parse_slack_login_data parsed them all. Got the idea from some code here on github but have tested it now (and I don't see it fixed in master).  I couldn't find the issue any more where I got the idea from.  
Large teams shouldn't try to parse all the login data in between getting the WS URL and connecting to the WS URL (as there is a timeout for the valid period of that URL).
This change is to move the connect to WS above the parse.
> Fixes an issue where ws connection failure for big teams.

- README.rst
- docs-src/basic_usage.rst
Adds support for posting ephemeral messages
> Add chat.postEphemeral to README and basic_usage

- slackclient/client.py
1.0.8 release broke `rtm_send_message` due to a misplaced shannel ID reference.
> Fixed rtm_send_message channel ID

- docs-src/real_time_messaging.rst
- docs/real_time_messaging.html
Fix link to rtm.connect docs in `docs-src/real_time_messaging.rst`
> Fix link to rtm.connect docs

- README.rst
fixes #165
Python 3 is now supported!
> removes statement about future python 3 support

- slackclient/client.py
Currently in the rtm_send_message function in client.py, if the channel is not found
```
channel_id = found_channel.id if found_channel.id else channel
```
generates the following error.
```
File "/venv/lib/python3.6/site-packages/slackclient/client.py", line 160, in rtm_send_message
channel_id = found_channel.id if found_channel.id else channel
AttributeError: 'NoneType' object has no attribute 'id'
```
This patch fixes the error by removing the 'id' attribute from the if statement.
* [x ] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/python-slackclient/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ x] I've read …
> Fix rtm_send_message bug

- slackclient/server.py
Fixes #227 
Removing an unused exception class, which is also misspelled.
> Removed unused exception class, fixes #227

- slackclient/server.py
It is quite useful to have these exceptions contain the reply
that caused the failure (especially for example when checking
for a 429 status code and backing off further requests). Right
now it is impossible to determine what the underlying issue
was and react appropriatly to it.
* [ x ] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/python-slackclient/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ x ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
> Add http reply into slack login and slack connection error

- slackclient/client.py
- slackclient/exceptions.py
- slackclient/server.py
Adding new error types to describe errors.
`SlackClientError` is the base class for all errors thrown from this package. It provides a generic default message if none is provided.
`ResponseParseError` is an error for Web API responses which cannot be parsed as JSON. Its message includes the response body and the message for the exception it wraps.
I attempted to follow best practices according to [this guide](https://julien.danjou.info/blog/2016/python-exceptions-guide).
I could spend some time writing tests, but I wanted to get this PR submitted for code review ASAP.
FYI: The new error types are in a new namespace called `.exceptions`. The existing custom error types `SlackConnectionError` and `SlackLoginError` should be moved under this namespace, but cannot be moved without bumping the …
> adds new SlackClientError and ResponseParseError types

- slackclient/slackrequest.py
- tests/test_slackrequest.py
To further the support for JSON POST on Web API endpoints, I've moved the auth token into a request header in lieu of passing it as a form param. the `api_call` signature remains the same.
See #253
> Moved `token` into Authorization header

- docs/basic_usage.html
Change the displayed text of a link to the linked method's name instead of the one from the previous section.
> Fix copy-and-paste error in docs

- slackclient/server.py
Edit to the comment describing the 3 minutes RTM's reconnect logic 
Edit to the error message thrown after 5 rate limited connection attempts to the RTM
> update RTM rate limiting comment and error message

- slackclient/client.py
Instead of just outputting to stderr the rtm connect
failure it is more appropriate to use the python logging
system and output a appropriate message (and pass in
exc_info=True so that the traceback gets logged as well).
* [ x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/python-slackclient/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
> Use logging instead of traceback

- docs-src/basic_usage.rst
- docs/basic_usage.html
Fixes the `file.upload` link in the basic usage docs. Resolves #355.
> Update `files.upload` link in docs

- setup.py
This is a temporary fix to resolve issues with the most recent `websocket-client` 0.55.0 release.
Related Issues:
https://github.com/slackapi/python-slackclient/issues/385
https://github.com/slackapi/python-slackclient/issues/386
> Lock websocket-client version: temp fix for #385

- slackclient/server.py
- test_requirements.txt
- tests/test_server.py
> Return an empty dict when response is empty instead of throwing an error

- README.md
- slack/version.py
- tutorial/PythOnBoardingBot/requirements.txt
Bumping version and updating Readme.
> v2 Release

- slack/web/base_client.py
- tests/web/test_web_client.py
Since `v2.0.0`, the package identifier in each request (embedded in the `User-Agent` header) changed from `slackclient` to `slack`. This change was not intentional, it was incidental on the fact that the code read the identifier from the module name using the magic variable `__name__`.
That change introduces issues in how Slack measures the usage of this tool. `slack` lacks the uniqueness, since other tools including the Desktop apps report themselves as `slack`. This forces classification of a request to require knowing the entire User Agent header to look for `python` alongside `slack` to distinguish. Ideally, the parsing logic can break the User Agent string on spaces, and classify each portion separately. It also creates a discontinuity so we cannot measure v2.x next to v1.x and other …
> Modify package identifier in user agent to match v1.x identifier

- README.md
Otherwise there seems to be a consistent exception being thrown:
> TypeError: __init__() takes 1 positional argument but 2 were given
> Specify "token" argument name in example code block in `README.md`.

- slack/web/client.py
There was a typo in the method name for `chat.ScheduleMessage` as it was in as `chat.ScheduledMessage`. Updated and confirmed the other Scheduled API endpoints are correct
> fixed typo in Scheduled message

- tutorial/03-responding-to-slack-events.md
The `WebClient` methods require keyword arguments, but the tutorial documentation omits the `user` keyword argument to `WebClient.im_open`, which might cause someone following the tutorial to encounter an error like this.
```python
TypeError: im_open() takes 1 positional argument but 2 were given
```
This PR resolves that by adding the `user` keyword argument.
> Use kwarg for web_client.im_open in tutorial docs

- .gitignore
- slack/rtm/client.py
- slack/web/base_client.py
- slack/web/client.py
- tests/rtm/test_rtm_client.py
- tests/rtm/test_rtm_client_functional.py
When using `RTMClient#typing()`, the typing indicator was not being sent immediately because the function was not asynchronous. This caused the erroneous behavior described in #415. In order to immediately send any data over the websocket with aiohttp we must use an async function.
This PR changes both `#typing()` and `#ping()` functions on the `RTMClient` class into async functions.
Here's an example of what this would look like implemented:
```Python
@slack.RTMClient.run_on(event="open")
async def typing_message(**payload):
rtm_client = payload["rtm_client"]
await rtm_client.typing(channel="C01234567")
```
It's a minor but still backwards-incompatible change.
> Fixing 415 - Converting the typing function to async

- README.md
- slack/rtm/client.py
- slack/web/base_client.py
- slack/web/client.py
- tests/helpers.py
- tests/rtm/test_rtm_client_functional.py
- tests/web/test_web_client.py
- tutorial/PythOnBoardingBot/app.py
- tutorial/PythOnBoardingBot/requirements.txt
RTMClient:
1. Updated the send_over_websocket method to use the same event loop.
2. Added back a method `_execute_in_thread` to executescallbacks in a separate thread for non-async methods.
WebClient:
1. Fix a bug where we incorrectly created a new event loop regardless if there was already a loop running.
2. Added `charset` to the headers to prevent the missing charset warning from Slack.
3. Refactored how we opened and closed files because the file has to be open while it's being transported.
4. Added a Future return type to the Web API methods.
Other updates:
1. Updated ReadMe to include details around how to install optional extras.
2. Added optional headers attributes to the RTM and Web clients.
3. Minor test updates.
> Fixing bugs that were recently introduced in master

- slack/web/client.py
Adds methods and types related to Slack's new Remote Files API. Learn more: https://api.slack.com/messaging/files/remote
Admins of enterprise grid organizations can also now use the Web API to approve, restrict, or list app installation requests. Learn more: https://api.slack.com/admins/managing
> Adding new admin and remote files API methods.

- README.md
Fix link to Auth Guide in readme
Before:
[After](https://github.com/asherf/python-slackclient/tree/readme):
> Fix link to Auth Guide in readme

- slack/web/classes/attachments.py
- tests/web/classes/test_attachments.py
Fixes a bug in #400; the base Attachment class that BlockAttachment inherits from will populate the `fields` attribute with an empty list, which then gets sent in the JSON to Slack. That makes the JSON invalid, meaning the BlockAttachment class as it is now cannot be used without manually adjusting the JSON/dict returned.
This PR updates the class, as well as adds a test that would have caught this.
> Update BlockAttachment to not send invalid JSON due to fields attribute

- slack/rtm/client.py
- tests/rtm/test_rtm_client.py
Returns the callback passed into `RTMClient.run_on` so that it can be called elsewhere. For example:
```python
@RTMClient.run_on("message")
def magic(**payload):
print('🔮')
magic()
```
> Fixes #485.
> Return callback from `RTMClient.run_on`

- README.md
This pull request improves the RTM code snippet on README. Currently, the code fails every time a bot message is posted with KeyError as below:
```
(omitted)
File "app.py", line 11, in say_hello
if data and 'Hello' in data['text']:
KeyError: 'text'
```
> Improve a code snippet on README

- slack/web/classes/elements.py
- tests/web/classes/test_elements.py
Bugfix for max value length in button elements. Documentation indicates 2000, the code however permits no more than 75 characters.
> bugfix for value length in button elements

- README.md
Fix Indentation of Code Snippets in README.md and make it consistent with other usage which has correct indentation.
3 out of 5 total code snippets have extra indentation added, which is not consitent with the two other snippets with seemingly correct indentation in README.md
> Fix Indentation of Code Snippets in README.md

- slack/web/slack_response.py
- tests/web/test_web_client.py
For Web Client, since `SlackResponse` class overrides an initial response data when iterating through the response object, it only returns the last fetched response data when it's iterated twice.
```py
import slack
client = slack.WebClient(token='redacted')
response = client.channels_list(limit=50)
print('#### 1st iteration ####')
for i in response:
print(i['channels'][0]['id'])
print('#### 2nd iteration ####')
for i in response:
print(i['channels'][0]['id'])
```
```sh
C9A81JQQ4
CB2LQDJTB
CB34D9SQ3
CB3BF4953
CB48SJH1V
CB48SJH1V
```
```sh
C9A81JQQ4
CB2LQDJTB
CB34D9SQ3
CB3BF4953
CB48SJH1V
C9A81JQQ4
CB2LQDJTB
CB34D9SQ3
CB3BF4953
CB48SJH1V
```
> Fix Web Client custom iterator

- slack/errors.py
- slack/web/base_client.py
- slack/web/client.py
- slack/web/slack_response.py
- tests/helpers.py
- tests/web/test_web_client.py
Fixing https://github.com/slackapi/python-slackclient/issues/481 by properly passing oauth params with `aiohttp.BasicAuth`.
Fixing https://github.com/slackapi/python-slackclient/issues/436 by returning the entire SlackResponse in SlackApiError's.
> :facepalm: Fixing issues around Oauth and SlackApiErrors

- slack/rtm/client.py
- slack/web/base_client.py
- slack/web/client.py
Adding new `views.publish` API.
Some responses don't return json. Correcting initial assumption. This fixes #493 & #535
> New Views API & Updates for internal request method

- slack/web/base_client.py
Make sure we do not close the running session
We must only close the temporary session used for the request.
Fixes: 854920dfb2a2
Signed-off-by: Fatih Acar <f.acar@criteo.com>
Latest release (v2.3.0) introduced a regression which make our slack app crash.
The associated traceback looks like:
```
File "/home/f.acar/hwinfo-slackbot/venv/lib64/python3.6/site-packages/slack/rtm/client.py", line 334, in _connect_and_read
proxy=self.proxy,
File "/home/f.acar/hwinfo-slackbot/venv/lib64/python3.6/site-packages/aiohttp/client.py", line 1012, in __aenter__
self._resp = await self._coro
File "/home/f.acar/hwinfo-slackbot/venv/lib64/python3.6/site-packages/aiohttp/client.py", line 728, in _ws_connect
proxy_headers=proxy_headers)
File …
```
> Fix regression in v2.3.0

- slack/web/base_client.py
- slack/web/client.py
- tests/web/test_web_client.py
With the new Slack apps preview bot users can request the same scopes as user tokens. Because of this, I believe validating xoxp token for requests no longer makes sense.
The `BotUserAccessError` exception is currently blocking users from trying out the new bot scopes introduced in the Slack apps preview.
This commit has a breaking change since API functions will no longer raise `BotUserAccessError` but this behavior was not documented as only `SlackRequestError` is mentioned in the docstrings.
If removing the exception is not preferred I can also implement a solution where the `WebClient` constructor has an option to disable this exception. Let me know 😊
> Remove _validate_xoxp_token

- slack/rtm/client.py
- slack/web/base_client.py
- slack/web/client.py
- slack/web/slack_response.py
Several python files in the library share a common commented header with a typo. This PR corrects from 
"""A Python module for iteracting with Slack's RTM API."""
to
"""A Python module for interacting with Slack's RTM API."""
> Fixed 'iteracting' typo in library file headers

- slack/web/classes/elements.py
- tests/web/classes/test_elements.py
> Remove value from LinkButtonElement

- slack/web/client.py
Adding new endpoints:
- admin.teams.admins.list
- admin.teams.owners.list
- admin.teams.create
- admin.users.assign
- admin.users.invite
- admin.users.remove
- admin.users.setAdmin
- admin.users.setOwner
- admin.users.setRegular
- admin.inviteRequests.*
> Adding new admin.* API's

- docs/conversations.html
Typo in conversations reference page. In example for `conversations_list`, example given for `types` parameter is 
`"public_channels, private_channels"`
Whereas it should be 
`"public_channel, private_channel"`
> Update docs/conversations.html - typo in API reference

- slack/rtm/client.py
- slack/web/base_client.py
If tokens contain whitespace, API calls fail in a confusing manner. See #598.
This change simply strips whitespace from tokens, to avoid confusing failures.
> Strip token string parameters of whitespace

- MANIFEST.in
A `py.typed` file was requested in #524 and added in #541. Unfortunately, as far as I can tell, it's not included with the package distribution and thus doesn't help end users yet. [PEP 0561](https://www.python.org/dev/peps/pep-0561/#packaging-type-information) mentions adding the file in `setup.py` with the `package_data` key, however, you're using `include_package_data` already, so I believe modifying `MANIFEST.in` is the correct change to make.
Please feel free to test things out, I'm not very familiar with typical Python packaging practices. I believe as long as the `py.typed` file gets included in the published package, we should be good to go, and end users should be able to get type-checking automatically for this package.
> Add py.typed file to package distribution

- slack/web/classes/elements.py
- tests/web/classes/test_elements.py
This pull request fixes a bug reported at #635.
> Fix #635 DatePickerElement initial_date validation is incorrect

- setup.py
- slack/web/base_client.py
- slack/web/client.py
- tests/web/test_web_client_coverage.py
This pull request fixes #634 by adding support for 9 admin methods. Also, I've added a test `test_web_client_coverage.py` to verify if there are no missing API methods.
> Fix #634 by adding missing method supports

- tutorial/PythOnBoardingBot/app.py
This is to fix some bug in the tutorial code:
1. WebClient#im_open expects positional user argument
> im_open requires positional arg, user key gives user_id

- slack/web/base_client.py
When invoking `api_call()`, the default value for `headers` is a mutable
object! If at any point during invocation, `api_call` mutates this
dictionary, it will affect the behavior of future calls to the method.
Thankfully, the current source does not modify `headers`, so this
adverse behavior does not happen.
However, it's a much safer pattern (and consistent with the rest of this
file) to use `None` as the default argument, and construct a new
dictionary as required.
See: https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments
> Use a non-mutable default headers argument

- slack/rtm/client.py
When trying to start a RTM connection over a thread a RuntimeError appears:
RuntimeError: set_wakeup_fd only works in main thread
This change allows it.
Issue: #605
> Allow running RTM over a thread

- integration_tests/web/test_issue_594.py
- slack/web/client.py
This pull request fixes #594 by adding support or `preview_image` parameter for `files.remote.add` API method calls.
In another PR #653 , I'm working on integration tests to enable us to verify if changes work with real APIs as expected. [This commit](https://github.com/slackapi/python-slackclient/pull/653/commits/399f89b523296cd966343d8022a0abaf68ae7a54) in that PR adds a test case for this issue and I've already verified this PR's patch fixes the issue.
After merging #653 ,  I will merge this PR as well.
Reference: https://api.slack.com/methods/files.remote.add
> Fix #594 preview_image for files.remote.add API method is not properly supported

- slack/web/client.py
This pull request fixes #660 by correcting the way to handle the `channel_ids` parameter. It needs to be a comma-separated list of channel IDs in a single string value.
https://api.slack.com/methods/admin.users.invite#arg_channel_ids
> Fix #660 channel_ids in admin.users.invite calls doesn't work

- tests/web/test_slack_response.py
This pull request just adds a sample demonstrating how to use `response.data`. 
I was going to implement the `__contains__` dunder method at the top level of `SlackResponse` (suggestion at #559) but I came to think it may result in unexpected behavior for other use cases and `key in response.data` is also simple enough.
Let me close #559 after merging this sample.
> Add a test demonstrating how to use response.data ref #559

- slack/web/classes/__init__.py
- tests/web/classes/test_init.py
This pull request corrects the type hints given to `slack.web.classes.extract_json`.
> Correct type hints for extract_json method

- integration_tests/rtm/test_issue_558.py
- slack/rtm/client.py
This pull request fixes #558 #619.
The cause of the issue addressed by this pull request is that the current implementation of `RTMClient` handles incoming WebSocket messages one by one (=sequentially). As a result, the following code blocks other handlers until the sleep time (10 seconds) passes.
```python
@RTMClient.run_on(event="message")
async def process_messages(**payload):
self.logger.debug(payload)
await asyncio.sleep(10)  # this used to block all other handlers
```
This pull request changes the internals of `RTMClient` a bit to accept simultaneous text messages. Error events and connection close events should not be executed asynchronously.
@stevengill @aoberoi @shaydewael 
As #665 and this pull request have a conflict, I need to merge them into one. But I think having reviews …
> Fix #558 #619 by revising RTMClient to accept simultaneous incoming messages

- slack/web/classes/objects.py
- tests/web/classes/test_objects.py
Per the date formatting documentation[1], any date links should be
prefixed with "<!date^" before the epoch and other information.
Currently this is not included in the rendering of a DateLink text
representation, which breaks rendering of dates within Slack.
Fixes: #676
[1]: https://api.slack.com/reference/surfaces/formatting#date-formatting
> Fix rendering of DateLink objects

- integration_tests/web/test_issue_670.py
- slack/web/base_client.py
This pull request fixes #670 by scanning None values from data, files, and params. There is no reason to keep them as they'll just result in TypeError.
After applying this change, the new sync mode WebClient in #662 also needs to be updated in the same manner.
> Fix #670 by removing all None values from dict

- slack/web/__init__.py
- slack/web/base_client.py
- tests/web/test_web_client_coverage.py
This pull request adds the warnings telling API deprecations. #650 
I've extracted this change from PR #662 . And the change already has been reviewed by @stevengill so that let me merge this PR.
https://github.com/slackapi/python-slackclient/issues/650#issuecomment-623751938
> Fix #650 Deprecation warnings to channels/groups/mpim/im API method calls

- slack/web/client.py
- tests/web/test_web_client_coverage.py
Currently, Some API methods in `WebClient` accept only str values for "channel_ids", "users" etc while others accept list values for those. This pull request improves them to be more consistent. Also, this pull request fixes #444 .
> Change list args to be either str or list in a consistent manner

- integration_tests/web/test_issue_560.py
- slack/web/__init__.py
- slack/web/base_client.py
- tests/web/test_web_client.py
To reduce the diff in #662, I've extracted the fix for #560 as this pull request. This pull request resolves #560 by having a conversion logic of bool values in `WebClient`. java-slack-sdk does the same here: https://github.com/slackapi/java-slack-sdk/blob/v1.0.7/slack-api-client/src/main/java/com/slack/api/methods/RequestFormBuilder.java#L1767-L1769
> Fix #560 Allow bool kwargs

- slack/web/classes/dialog_elements.py
It started failing with flake8 version 3.8.0. As it seems a reasonable warning, let me modify the existing class to settle it.
> Fix the lint errors reported by latest flake8

- slack/signature/__init__.py
- slack/signature/verifier.py
- slack/web/base_client.py
- tests/signature/test_signature_verifier.py
This pull request adds the official implementation of Slack request verification. We have been having this logic as a static method in `BaseClient` but it's not the right place to have it. 
When we release version 2.6.0 with this change, I'll update this part of the document. https://slack.dev/python-slackclient/basic_usage.html#opening-a-modal
> Add SignatureVerifier for request verification

- docs-src/basic_usage.rst
- integration_tests/samples/basic_usage/views.py
- slack/signature/verifier.py
- tests/signature/test_signature_verifier.py
This pull request applies a minor improvement to #686 by having consideration for the "body" parameter as a `bytes` value. Also, it updates to the related document.
> Additional improvements for #686 and document updates

- docs-src/changelog.rst
After merging #662 #686 , we can release v2.6.0rc1. I'll run `./docs.sh` when releasing the version.
> Add v2.6.0rc1 release note

- integration_tests/samples/basic_usage/views_2.py
- slack/web/classes/views.py
- slack/web/client.py
- tests/web/classes/test_views.py
- tests/web/test_web_client_coverage.py
@ruberVulpes
Thank you very much for your great feedback: https://github.com/slackapi/python-slackclient/issues/519#issuecomment-629733995
This pull request adds more validation rules in `View` objects to let developers know errors with more sufficient information. Also, I've updated the `views_open` API method in `WebClient` to accept `View` objects as well.
> Add more validation rules for view construction (thanks to feedback in #519)

- integration_tests/samples/issues/issue_690.py
- slack/web/base_client.py
- tests/web/mock_web_api_server.py
- tests/web/test_web_client.py
This pull request fixes #690 by resolving the lack of basic auth header generation when `run_async=False`. This lack of implementation used to result in `oauth.v2.access` and `oauth.access` API call failures.
> Fix #690 by adding basic auth handling in the new sync client

- slack/web/base_client.py
This pull request fixes #692 by removing an unnecessary part form `Content-Type` header when the value is `application/x-www-form-urlencoded`.
> Fix #692 superfluous_charset warnings

- slack/web/classes/objects.py
- tests/web/classes/test_objects.py
This pull request adds the missing `confirm.style` in block elements.
https://api.slack.com/reference/block-kit/composition-objects#confirm
> Add style to confirm in a block element

- .deepsource.toml
- integration_tests/rtm/test_issue_558.py
- integration_tests/rtm/test_issue_701.py
- slack/rtm/client.py
This pull request reverts #667 as the change in the PR caused another issue reported at #701 . I will be reopening #558 #619 and those issues may be resolved by another approach in the future.
> Fix #701 by reverting the change for simultaneous request handling

- slack/web/slack_response.py
- tests/web/test_web_client.py
This pull request fixes #705 by modifying `SlackRepsonse` to consider possible None values in `req_args` dict.
> Fix #705 by modifying SlackResponse to consider None value in dict

- integration_tests/samples/oauth/oauth_v2.py
- integration_tests/web/test_web_client.py
- slack/web/base_client.py
- tests/web/test_web_client.py
This pull request fixes #536 by adding token argument support in `BaseClient#api_call` method. This change enables developers to pass an access token for each request.
```python
from slack import WebClient
bot_token = "xoxb-***"
client = WebClient(token=bot_token)
user_token = "xoxp-***"
result = client.search_all(token=user_token, query="pickleface")
```
> Fix #536 Allow Tokens to be specified per request

- integration_tests/samples/basic_usage/views_default_to_current_conversation.py
- slack/web/classes/elements.py
- tests/web/classes/test_elements.py
This pull request fixes #708 by adding the `default_to_current_conversation` flag to (multi_)conversations_select block elements. This enables developers to fill the current conversation in the `initial_converstaion` when opening a modal (from shortcuts, buttons, and slash commands).
> Fix #708 default_to_current_conversation in (multi_)conversations_select

- README.md
- slack/web/base_client.py
After upgrading from slackclient 2.5.x to 2.6.x I was getting `CERTIFICATE_VERIFY_FAILED` when making requests to Slack. I think this is because of the switch to using `urllib` for sync requests, which isn't using the passed SSL context, which I am using. This makes sync requests use the passed SSL context. The other changes are as far as I can tell from auto-formatting with `black` being enabled in the VS Code settings.
I also updated the README for clarity. The SSL documentation seemed ambiguous to me before. The impression I got was that you _must_ use the `ssl` kwarg to have the requests to Slack use SSL, which seemed odd to me.
I wasn't able to get the tests to run, so I've only tested this by running against a live Slack instance.
Lastly, I haven't looked into it much but I think …
> Use SSL context with sychronous requests

- README.md
- integration_tests/samples/issues/issue_714.py
- integration_tests/web/test_issue_714.py
- slack/web/base_client.py
This pull request fixes a regression in v2.6.0 #714
> Fix #714 by adding proxy support for sync WebClient

- slack/web/base_client.py
- slack/webhook/client.py
- tests/web/mock_web_api_server.py
- tests/web/test_web_client.py
- tests/webhook/mock_web_api_server.py
- tests/webhook/test_webhook.py
This pull request fixes a regression in v2.6.0 #712. Also, it fixes the same issue with `WebhookClient`.
> Fix #712 by adding timeout arg support in sync WebClient/WebhookClient

- setup.py
As [this build result shows](https://travis-ci.org/github/slackapi/python-slackclient/jobs/699542509), the CI builds with Python 3.6 and 3.7 started failing due to the mismatching versions of `pytest` and its extensions. 
The direct cause of the error is that somehow the dependency resolver is stick with `pytest` 4.3 even though other dependencies require python 4.6+, plus, it's technically possible to automatically upgrade `pytest` version (as with python 3.8 does). 
Also, how `pip` determines which `pytest` version to use depends on the environment. For instance, we cannot reproduce this behavior on macOS, as far as I know.
To fix this, being more specific about the major versions of dependencies is the easiest and the most straight-forward way. The change in this PR affects only the …
> Set a specific range of test dependency versions to make builds more stable

- slack/web/classes/blocks.py
- slack/web/classes/views.py
Fix some a bug in `InputBlock` label and fix `View` title type (should accept string).
> Text params at "InputBlock" and "View"

- setup.py
Recommendations [1] from upsteam is to not include pytest_runner for all
invocations of setup.py.  This will result in delays and unneeded
downlaods.
[1] https://github.com/pytest-dev/pytest-runner/#considerations
For packaging systems this extra download isn't required.
> Only require pytest_runner if tests are run

- integration_tests/web/test_issue_728.py
- slack/web/base_client.py
This pull request fixes #728 by adding `bytearray` type support for file-type parameters. This issue has been an incompatibility issue when using `run_async=False` (the default) mode since v2.6.0
> Fix #728 by adding bytearray support in files_upload (sync mode)

- slack/web/classes/elements.py
- tests/web/classes/test_elements.py
Fix for the issue:
https://github.com/slackapi/python-slackclient/issues/744
> DatePickerElement - initial date. Fixed regex error, so it can accept 10 and 20 for day value now.

- slack/web/base_client.py
- tests/web/mock_web_api_server.py
- tests/web/test_web_client.py
This pull request fixes #718 by adding the logic to handle non-JSON response body data in `WebClient` (both sync and async). Although the situation almost never happens, raising only the errors defined in this SDK is more developer-friendly. Refer to the issue for details and use cases.
> Fix #718 by handling unexpected response body format

- slack/rtm/client.py
This pull request fixes #733. As the situation is not so easy to reproduce, I didn't write unit tests for this change. I'm sure the change is safe enough, though.
> Fix #733 Better error handling when getting TimeoutError in RTMClient#start()

- slack/web/classes/blocks.py
- tests/web/classes/test_blocks.py
This pull request fixes #767 by adding header block support to the `slack.web.classes.blocks` module as `HeaderBlock`.
- ⛑ Included a test that is based on the other block tests
- 🔍 Validated the `text` field as required with max length of 3000 characters
- 🔍 Validated the `block_id` field as optional
- 📐 Tried my best to match the ordering that the blocks were implemented (e.g. alphabetical or chronological)
- 📝 I did not find any documentation that needed to be updated, but please let me know if I missed a file!
> [Fix #767] Add header block support

- integration_tests/web/test_issue_770.py
- slack/web/base_client.py
This pull request fixes #770. Refer to the issue for details.
> Fix #770 by adding bytes type param support

- slack/web/classes/blocks.py
- tests/web/classes/test_blocks.py
While reviewing #768 , I found that `CallBlock` is not yet supported in `Block.parse(dict)` method. The block class was introduced by #704. I missed changing the class method in the PR.
> Correct Block.parse(dict) to support CallBlock

- slack/web/__init__.py
- slack/web/async_base_client.py
- slack/web/async_internal_utils.py
- slack/web/base_client.py
- slack/webhook/async_client.py
- slack/webhook/client.py
- slack/webhook/internal_utils.py
- tests/web/mock_web_api_server.py
- tests/web/test_async_web_client.py
- tests/web/test_web_client.py
- tests/webhook/mock_web_api_server.py
- tests/webhook/test_async_webhook.py
- tests/webhook/test_webhook.py
This pull request adds the functionality to add prefix/suffix to User-Agent request header in API requests to Slack API Platform. It fixes the issue #769.
> Fix #769 by supporting prefix/suffix for User-Agent

- slack/web/async_client.py
- slack/web/client.py
- tests/web/test_web_client_coverage.py
I wanted to make these changes to get auto-fill when using the slackclient in my IDE. I based the required/optional parameter style off of `chat_postMessage`
It also looks like when I ran `python setup.py validate` black formatted a few more files than I would expect
* `admin_conversations_restrictAccess_addGroup`
* Added arguments `channel_id` and `group_id`
* Added doc strings for arguments based on [documentation ](https://api.slack.com/methods/admin.conversations.restrictAccess.addGroup)
* `admin_conversations_restrictAccess_listGroups`
* Added arguments `channel_id` 
* Added doc strings for arguments based on [documentation ](https://api.slack.com/methods/admin.conversations.restrictAccess.listGroups)
* `admin_conversations_restrictAccess_removeGroup`
* Added arguments `channel_id`, …
> Fix admin.conversations.restrictAccess.* methods to match documentation

- slack/web/classes/elements.py
This PR aims to fix a broken link.
> Fix a link to the Static options documentation

- integration_tests/web/test_admin_conversations.py
- slack/web/async_client.py
- slack/web/client.py
This pull request applies two minor improvements in addition to #795 
* Move the added methods at the bottom to the right position (it's okay not to be strictly in alphabetical order, though)
* Add more conditions/assertions to search tests
> Minor improvements to admin.conversations.* support

- slack/web/async_client.py
- slack/web/client.py
Fixes #809
3ef65f39461855394fd02de20f55aca5f14b6b88 changed [files_upload](https://github.com/slackapi/python-slackclient/blob/033fb44f64d5c5f5664a8b6752adf3e4beba7854/slack/web/client.py#L1473) behavior to always set default filename regardless of instace type of file input parameter. If file is of type IOBase, which the type hinting indicates is supported, [#L1496](https://github.com/slackapi/python-slackclient/blob/033fb44f64d5c5f5664a8b6752adf3e4beba7854/slack/web/client.py#L1496) would raise an exception when trying to call `split` on a non-string type. Since the Slack API files_upload does not require a filename to upload, I do not believe this method should either.
No unit tests added as this code change should still be coverd by …
> Only set default filename in files_upload if file is an instance of str

- .coveragerc
- .deepsource.toml
- slack_sdk/errors/__init__.py
- slack_sdk/models/attachments/__init__.py
- slack_sdk/models/basic_objects.py
- slack_sdk/models/blocks/__init__.py
- slack_sdk/models/blocks/basic_components.py
- slack_sdk/models/blocks/block_elements.py
- slack_sdk/models/blocks/blocks.py
- slack_sdk/models/dialoags/__init__.py
- slack_sdk/models/messages/message.py
- slack_sdk/models/views/__init__.py
- slack_sdk/rtm/__init__.py
- slack_sdk/signature/__init__.py
- slack_sdk/web/base_client.py
- slack_sdk/web/client.py
- slack_sdk/web/legacy_base_client.py
- slack_sdk/web/legacy_slack_response.py
This pull request fixes (or skips) DeepSource warnings before adding more changes to the branch.
> Fix or skip DeepSource warnings

- slack/web/base_client.py
- slack/webhook/client.py
As reported at #820 #821 , the current implementation of `WebClient`/`WebhookClient` when enabling `proxy` option started failing to send requests to the Slack API server. The implementation introduced by #715 has been working with the server-side for three months but it doesn't  work anymore. 
Other HTTP clients don't fail and the changes on the server-side look valid to me. I found that the implementation can be corrected in the way this PR does.
This issue is affecting some users in production. So, I will quickly release a new patch version after verifying the CI builds and running all the integration tests. 
Then, the affected users can deal with this issue by either of:
* Upgrade to the next patch version (2.9.1)
* Use `HTTPS_PROXY` environment variable over the `proxy` option in …
> Fix proxy issue reported at #820 #821

- slack/web/classes/blocks.py
- tests/web/classes/test_blocks.py
`text` field validation in `header` blocks introduced by #768 has not been working. This pull request corrects the implementation to use the max length. 
In addition, this PR adjusts the upper limit. The max length in the document (3000) is incorrect (or outdated). The actual behavior is up to 150 characters. The API document team is going to update the page soon.
cc @mwbrooks (as the author of #768)
> Correct the text validation in header blocks

- tutorial/04-running-the-app.md
In issue slackapi#830, a developer tried to DM the bot and didn't
receive a response because the 'message.im' event was not used.
This tutorial only uses 'message.channels', so the bot must be
invited to a public channel to receive the "start" message.
This commit clarifies that the bot must be invited to a public channel
for the `v3` docs.
> [#830] Clarify channel type in v3 docs for Running the App

- tutorial/04-running-the-app.md
In issue #830, a developer tried to DM the bot and didn't
receive a response because the 'message.im' event was not used.
This tutorial only uses 'message.channels', so the bot must be
invited to a public channel to receive the "start" message.
This commit clarifies that the bot must be invited to a public channel.
> [#830] Clarify channel type in docs for Running the App

- slack/web/base_client.py
- slack/webhook/client.py
- tests/web/mock_web_api_server.py
- tests/web/test_async_web_client.py
- tests/web/test_web_client.py
- tests/web/test_web_client_issue_829.py
- tests/webhook/mock_web_api_server.py
- tests/webhook/test_webhook.py
This pull request fixes #829 by adding default values for the charset that is supposed to be used for parsing response body from Slack. The situation may arise either when the `content-type` header is missing or `content-type` header doesn't contain charset information in it.
We can safely assume "utf-8" is the one it can fallback in the case where the server-side cannot return a valid response.
> Fix #829 by adding the default encoding

- slack_sdk/models/blocks/basic_components.py
- slack_sdk/models/blocks/block_elements.py
- slack_sdk/models/blocks/blocks.py
- tests/slack_sdk/web/classes/test_blocks.py
- tests/slack_sdk/web/classes/test_elements.py
This pull request adds the new features described in #841 to the v3 branch.
> [v3] Add Dispatch Action in Block Kit #841

- slack/web/classes/blocks.py
- slack/web/classes/elements.py
- slack/web/classes/objects.py
- tests/web/classes/test_blocks.py
- tests/web/classes/test_elements.py
This pull request adds the feature described in #841 to 2.9 series.
> Add Dispatch Action in Block Kit #841

- slack/web/classes/blocks.py
Fixes #851 (at least for the main branch. This change needs to be applied to v3 branch in `slack` and `slack_sdk` respective locations)
> Set default_type for HeaderBlock text

- slack/rtm/client.py
> Fix #846 RTMClient does not pass timeout value to WebClient

- integration_tests/samples/issues/issue_868.py
- slack_sdk/models/__init__.py
- slack_sdk/models/attachments/__init__.py
- slack_sdk/models/blocks/basic_components.py
- slack_sdk/models/blocks/block_elements.py
- slack_sdk/models/blocks/blocks.py
- slack_sdk/models/dialoags/__init__.py
- slack_sdk/models/messages/message.py
- slack_sdk/models/views/__init__.py
- slack_sdk/oauth/authorize_url_generator/__init__.py
- slack_sdk/oauth/installation_store/models/bot.py
- slack_sdk/oauth/installation_store/models/installation.py
- slack_sdk/oauth/state_utils/__init__.py
- slack_sdk/rtm/__init__.py
- slack_sdk/web/async_client.py
- slack_sdk/web/async_internal_utils.py
- slack_sdk/web/client.py
- slack_sdk/web/internal_utils.py
- slack_sdk/web/legacy_client.py
- slack_sdk/webhook/async_client.py
- slack_sdk/webhook/client.py
- tests/slack_sdk_async/web/test_web_client_coverage.py
As reported at #868, some argument type hints are `List` and mypy points out that can be a potential issue. As this warning is reasonable enough, we are going to prefer `Sequence` type hint over `List` in arguments.
http://mypy.readthedocs.io/en/latest/common_issues.html#variance
This pull request fixes #868 for the classes under `slack_sdk` package.
> Fix #868 by changing List type hints to Sequence

- slack_sdk/oauth/state_store/state_store.py
This should allow for the creation of custom states where the additional data can be used to associate external accounts.
In order for additional data to be applied or associated during the creation of a `state` there needs to be access to situational information. One method would be to craft Class variables before the `issue` method call but adding the ability to include additional parameters directly at the time of calling has less code smell.
https://github.com/slackapi/bolt-python/issues/144#issuecomment-722931784
- [ x] **slack_sdk.oauth** (OAuth Flow Utilities)
- [x ] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/python-slack-sdk/blob/main/.github/contributing.md) and have done my best effort to follow them.
- [x ] I've read and agree to the …
> Enable additional data on state creation

- scripts/run_validation.sh
- setup.py
- slack_sdk/oauth/state_store/amazon_s3/__init__.py
- slack_sdk/oauth/state_store/async_state_store.py
- slack_sdk/oauth/state_store/file/__init__.py
- slack_sdk/oauth/state_store/sqlalchemy/__init__.py
- slack_sdk/oauth/state_store/sqlite3/__init__.py
- tests/slack_sdk/oauth/state_store/test_file.py
This pull request appends additional changes to #871
> Addition to #871: AsyncOAuthStateStore and built-in implementations

- slack_sdk/web/async_client.py
- slack_sdk/web/client.py
- slack_sdk/web/legacy_client.py
Fix simple typo, niether -> neither
> docs: Fix simple typo, niether -> neither

- slack_sdk/web/async_base_client.py
- slack_sdk/web/base_client.py
- slack_sdk/web/internal_utils.py
- slack_sdk/web/legacy_base_client.py
- tests/slack_sdk/web/test_web_client.py
- tests/slack_sdk_async/web/test_async_web_client.py
- tests/web/test_web_client.py
This pull request updates the Web API clients to hold the default `team_id` in each instance, aiming better support for Org-Wide App installation.
> Add default team_id to WebClient constructor args

- slack_sdk/models/blocks/block_elements.py
(Describe the goal of this PR. Mention any related Issue numbers)
- [X ] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/python-slack-sdk/blob/main/.github/contributing.md) and have done my best effort to follow them.
- [X ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
- [X ] I've run `python setup.py validate` after making the changes.
> Update PlainTextInputElement description

- tutorial/03-responding-to-slack-events.md
- tutorial/PythOnBoardingBot/app.py
- tutorial/PythOnBoardingBot/async_app.py
This pull request fixes a bug in the PythOnBoardingBot tutorial app reported at #889
> Fix #889 by correcting the team_join event handler

- tutorial/PythOnBoardingBot/app.py
This is a minor change. 
There is one line in the emoji callback and one line in the pin callback that are currently "do-nothing" operations (I believe). 
This  PR is to remove those "do-nothing" operations for the sake of clarity.
One underlying assumption of mine is that Slack uses (channel id, time stamp) as a unique ID for a Slack Message, and that these IDs (timestamps) don't change.
> the timestamp for Slack-post never changes, it is effectivly an ID

- docs-src-v2/conversations.rst
- docs-src/web/index.rst
- docs-v2/.buildinfo
- docs-v2/conversations.html
- docs/.buildinfo
- docs/web/index.html
This pull request updates the channel character limit from 21 to 80 chars. This was reported by our Slack support team, who recently found that our docs were still using the previous character limit.
I've updated this for both v2 and the latest documentation.
> Update channel char limit to 80

- slack_sdk/web/async_client.py
- slack_sdk/web/client.py
- slack_sdk/web/legacy_client.py
- tests/slack_sdk_async/web/test_web_client_coverage.py
This pull request updates the internals of `WebClient` to accept tuple values for ids arguments.
for context: https://github.com/slackapi/python-slack-sdk/pull/894#discussion_r541450730
> Update WebClient to accept not only list but also tuple

- slack_sdk/models/blocks/blocks.py
- tests/slack_sdk/web/classes/test_blocks.py
Fix [issue 903](https://github.com/slackapi/python-slack-sdk/issues/903)
> Fix #903 by parsing in ActionsBlock

- slack/web/classes/blocks.py
- tests/web/classes/test_blocks.py
Fix [issue 903](https://github.com/slackapi/python-slack-sdk/issues/903) for slackclient (v2) maintenance
> Fix #903 by parsing elements in ActionsBlock

- slack_sdk/web/internal_utils.py
- tests/slack_sdk/web/test_web_client_issue_900.py
> Fix #900 by correcting the WebClient behavior for Org-Wide Apps

- slack_sdk/web/async_client.py
- slack_sdk/web/client.py
- slack_sdk/web/legacy_client.py
This pull request fixes #901 by correcting the `file` arg's type hint.
> Fix #901 by correcting type hints for files_upload method args

- setup.py
- slack_sdk/aiohttp_version_checker.py
- slack_sdk/rtm/__init__.py
- tests/test_aiohttp_version_checker.py
This pull request adds aiohttp library validator to prevent the situation like #912 happening to many developers. After merging this PR, I will apply the same validation to Socket Mode client based on aiohttp in #883
> Add aiohttp version validation (ref #912)

- slack_sdk/webhook/async_client.py
- slack_sdk/webhook/client.py
- tests/slack_sdk/webhook/test_webhook.py
- tests/slack_sdk_async/webhook/test_async_webhook.py
This pull request fixes #919 by enhancing `WebhookClient#send()` method to have the following arguments:
* replace_original
* delete_original
(Describe the goal of this PR. Mention any related Issue numbers)
> Fix #919 Add replace_original/delete_original to WebhookClient (async/sync)

- slack_sdk/oauth/installation_store/models/bot.py
- slack_sdk/oauth/installation_store/models/installation.py
- tests/slack_sdk/oauth/installation_store/test_models.py
This pull request fixes #918 by adding the following methods to `Installation` and `Bot` classes.
* set_custom_value(name, value)
* get_custom_value(name)
Developers can save additional values as part of installation data by utilizing the `custom_values`.
> Fix #918 Enable to have additional fields in Bot/Installation instances

- slack_sdk/web/async_base_client.py
- slack_sdk/web/base_client.py
- slack_sdk/web/legacy_base_client.py
- slack_sdk/webhook/async_client.py
- slack_sdk/webhook/client.py
- tests/slack_sdk/web/test_web_client_issue_921_custom_logger.py
- tests/slack_sdk/webhook/test_webhook.py
- tests/slack_sdk_async/web/test_web_client_issue_921_custom_logger.py
- tests/slack_sdk_async/webhook/test_async_webhook.py
- tests/web/test_web_client_issue_921_custom_logger.py
This pull request fixes #921 by adding custom logger arguments to web clients and webhook clients. Refer to #921  for details.
> Fix #921 Enable to use custom logger in WebClient, WebhookClient (async/sync)

- integration_tests/samples/issues/issue_926.py
- slack_sdk/socket_mode/aiohttp/__init__.py
This pull request fixes #926 by improving the internals of aiohttp-based SocketModeClient.
@cxlai let me know if you have any comments / feedback on this implementation. I will merge this PR tomorrow and release a new patch version.
> Fix #926 Handle closing aiohttp.ClientSession in socket mode

- slack_sdk/audit_logs/v1/logs.py
- slack_sdk/scim/v1/group.py
- slack_sdk/scim/v1/internal_utils.py
- slack_sdk/scim/v1/types.py
- slack_sdk/scim/v1/user.py
- tests/slack_sdk/audit_logs/test_response.py
- tests/slack_sdk/scim/test_internals.py
- tests/slack_sdk/scim/test_response.py
This pull request applies improvements to the data classes in #940 #936 . Without this change, the JSON response data parser fails when the server-side introduces a new field to the data structure.
> Add unknown kwargs in SCIM / Audit Logs clients

- integration_tests/scim/test_scim_client_write.py
- slack_sdk/scim/v1/internal_utils.py
This pull request enables `SCIMClient` and `AsyncSCIMClient` to work with a dict argument using snake_cased keys. 
To make the argument compatible with the server-side, we need to convert the keys to camelCase strings. The implementation in v3.3.0 does not convert nested dict values.
Although we recommend using `User` class for API calls [this way](https://slack.dev/python-slack-sdk/scim/index.html#scimclient), using a dict value can be handier for partial updates (=PATH API calls).
> Enable to use snake_cased keys for dict arg in SCIMClient/AsyncSCIMClient

- slack_sdk/rtm/v2/__init__.py
When using RTM Client v2 and calling the `close` method an exception is raised.
```
File "/opt/errbot/bin/errbot", line 8, in <module>
sys.exit(main())
File "/opt/errbot/lib/python3.8/site-packages/errbot/cli.py", line 399, in main
bootstrap(backend, root_logger, config, restore)
File "/opt/errbot/lib/python3.8/site-packages/errbot/bootstrap.py", line 259, in bootstrap
bot.serve_forever()
File "/opt/errbot/lib/python3.8/site-packages/errbot/backends/base.py", line 882, in serve_forever
self.shutdown()
File "/opt/errbot/backends/err-backend-slackv3/slackv3.py", line 1230, in shutdown
self.slack_rtm.close()
File "/opt/errbot/lib/python3.8/site-packages/slack_sdk/rtm/v2/__init__.py", line 240, in close
self.disconnect()
File …
```
> Use self.current_session instead of inexistent self.connection

- integration_tests/samples/rtm_v2/rtm_v2_proxy_app.py
- integration_tests/samples/socket_mode/builtin_proxy_example.py
- integration_tests/samples/socket_mode/websocket_client_proxy_example.py
- slack_sdk/socket_mode/builtin/client.py
- slack_sdk/socket_mode/builtin/connection.py
- slack_sdk/socket_mode/builtin/internals.py
- tests/slack_sdk/socket_mode/mock_web_api_server.py
- tests/slack_sdk/socket_mode/test_builtin.py
This pull request fixes #948 by correcting the built-in SocketModeClient's proxy support. It also fixes #952
> Fix #948 built-in SocketModeClient does not support proxy

- integration_tests/samples/socket_mode/builtin_proxy_auth_example.py
- slack_sdk/socket_mode/builtin/internals.py
This pull request adds support for `{username}:{password}@` format in HTTP proxy URLs, in addition to #951 changes. This update improves the built-in `SocketModeClient`'s compatibility with `WebClient` etc for proxy auth configuration.
ref: #948
> Enable easier proxy auth configuration in built-in SocketModeClient

- integration_tests/samples/socket_mode/builtin_proxy_env_variable_example.py
- slack_sdk/audit_logs/v1/async_client.py
- slack_sdk/audit_logs/v1/client.py
- slack_sdk/proxy_env_variable_loader.py
- slack_sdk/rtm/v2/__init__.py
- slack_sdk/scim/v1/async_client.py
- slack_sdk/scim/v1/client.py
- slack_sdk/socket_mode/aiohttp/__init__.py
- slack_sdk/socket_mode/builtin/client.py
- slack_sdk/web/async_base_client.py
- slack_sdk/web/base_client.py
- slack_sdk/web/legacy_base_client.py
- slack_sdk/webhook/async_client.py
- slack_sdk/webhook/client.py
- tests/test_proxy_env_variable_loader.py
This pull request adds support for common `HTTPS_PROXY` / `HTTP_PROXY` env variables - related to #948 
This is mostly backward compatible as given `proxy` argument would be prioritized over env variables. However, if an app is running in the host which has the env variables and the application does not have `proxy` argument in constructors, its behavior could be changed. Thus, I think we should enable this in the next minor version (v3.4), not a patch version. Also, we can mention this in the release note.
> Add HTTPS_PROXY/HTTP_PROXY env variable support #948

- integration_tests/samples/oauth/oauth_v2.py
- integration_tests/samples/oauth/oauth_v2_async.py
- integration_tests/samples/oauth/oauth_v2_legacy.py
- slack_sdk/oauth/redirect_uri_page_renderer/__init__.py
This pull request improves the default HTML page for successful Slack app installation. I got a feedback from a customer, saying the person uses only the browser version of Slack and the `slack://` deep link navigation does not work for me at all. As this is a common use case, I see rooms for improvement on this feature.
We may want to apply the same (or similar) change to `@slack/oauth` npm package and the Java SDK's default behavior.
> Add the browser version link in redirect_uri web page

- slack_sdk/web/internal_utils.py
Check for an "attachments" argument and validate each "fallback" parameter instead of just checking for a top-level "text" argument.
Closes #965. 
(Describe the goal of this PR. Mention any related issue numbers)
> Improve validation of missing fallback text in payloads

- integration_tests/web/test_admin_analytics.py
- slack_sdk/web/async_client.py
- slack_sdk/web/client.py
- slack_sdk/web/legacy_client.py
This pull request updates the Web API clients to support newly added `public_channel` type and metadata_only arguments in the admin.analytics.getFile API.
see also: https://api.slack.com/methods/admin.analytics.getFile
> Add public_channel type support for admin.analytics.getFile API

- slack_sdk/web/internal_utils.py
- tests/slack_sdk/web/test_web_client_issue_971.py
Fixes #971.
Sorry about that. 😞
(Describe the goal of this PR. Mention any related issue numbers)
> Prevent breaking change when 'attachments' is a string.

- slack_sdk/web/internal_utils.py
- tests/slack_sdk/web/test_web_client_issue_971.py
This pull request applies some minor changes to #972
* Add some comments for its context
* Apply black code formatter to the added tests
cc @eddyg
> Add more comments to #972 changes and apply code formatter

- slack_sdk/models/attachments/__init__.py
- tests/web/classes/test_attachments.py
The attachments document encourages having `fallback` field in each attachment: https://api.slack.com/reference/messaging/attachments#legacy_fields
This pull request resolves the missing `fallback` argument in `BlockAttachment` constructor.
Thanks @eddyg for the feedback: https://community.slack.com/archives/CHL4CLRCZ/p1616013860007200
(if you're interested in joining the Slack workspace, you can join the community from https://j.mp/community-slack-com)
> Add fallback argument in BlockAttachment

- slack/web/base_client.py
- slack/webhook/async_client.py
- slack/webhook/client.py
- slack_sdk/audit_logs/v1/async_client.py
- slack_sdk/audit_logs/v1/client.py
- slack_sdk/oauth/installation_store/async_cacheable_installation_store.py
- slack_sdk/oauth/installation_store/cacheable_installation_store.py
- slack_sdk/rtm/v2/__init__.py
- slack_sdk/scim/v1/async_client.py
- slack_sdk/scim/v1/client.py
- slack_sdk/socket_mode/builtin/internals.py
- slack_sdk/web/base_client.py
- slack_sdk/web/internal_utils.py
- slack_sdk/web/legacy_base_client.py
- slack_sdk/webhook/async_client.py
- slack_sdk/webhook/client.py
This pull request is preparation for #980 API document hosting.
> Rewrite reStructuredText docstrings to use Google style

- integration_tests/web/test_admin_users_session_settings.py
- slack_sdk/web/async_client.py
- slack_sdk/web/client.py
- slack_sdk/web/legacy_client.py
- tests/slack_sdk_async/web/test_web_client_coverage.py
This pull request fixes #982 - refer to the issue for details.
> Fix #982 Add admin.users.session.* API support

- slack_sdk/scim/v1/async_client.py
- slack_sdk/web/async_internal_utils.py
- slack_sdk/web/base_client.py
- slack_sdk/web/internal_utils.py
- slack_sdk/web/legacy_base_client.py
- slack_sdk/webhook/async_client.py
- tests/slack_sdk/web/test_internal_utils.py
- tests/slack_sdk/web/test_web_client.py
- tests/slack_sdk/web/test_web_client_issue_829.py
- tests/web/test_web_client.py
- tests/web/test_web_client_issue_829.py
The current implementation outputs an error message saying "Failed to parse the response body: ..." when the Slack server-side returns non-JSON response body for some reasons. I think this error message could be confusing. In this scenario, no unexpected error on the API client side is occurring.
This pull request improves the error handling code to generate more precise error message in the above patterns. I will add some comments for reviewers.
> Improve error response body parser in WebClient

- slack_sdk/models/views/__init__.py
- tests/slack_sdk/models/test_views.py
This pull request adds a default `selected_options` attribute for `ViewStateValue` objects. This makes it consistent with the other attributes of this class. This is related to [Issue 987](https://github.com/slackapi/python-slack-sdk/issues/987).
> Setting a default value for select_options for ViewStateValue

- slack_sdk/models/blocks/basic_components.py
- tests/slack_sdk/models/test_objects.py
- tests/slack_sdk/models/test_views.py
This pull request resolves #990 . Refer to the issue for the details.
> Fix #990 slack_sdk.models.blocks.Option's description value is invalid in blocks

- slack_sdk/version.py
As we've completed all the planned tasks for v3.5 release, I will publish v3.5.0rc1 (pre release) to PyPI registry.
https://github.com/slackapi/python-slack-sdk/milestone/31?closed=1
With this pre-release version, I will start working on https://github.com/slackapi/bolt-python/issues/254
version 3.5.0
Since this version, the following methods are available to use for better installation data management.
* delete_bot / async_delete_bot
* delete_installation / async_delete_installation
* delete_all / async_delete_all
All the built-in implementations already support these methods. We recommend subscribing to `tokens_revoked` / `app_uninstalled` bot events and call these methods in the event handlers.
We recently started hosting the Python module documents at …
> version 3.5.0rc1 release

- slack_sdk/models/blocks/block_elements.py
This pull request resolves #1002
> Fix #1002 ConversationFilter missing new optional field exclude_external_shared_channels

- integration_tests/rtm/test_issue_569.py
- integration_tests/rtm/test_issue_605.py
- integration_tests/rtm/test_issue_631.py
- integration_tests/rtm/test_issue_701.py
- integration_tests/rtm/test_rtm_client.py
- slack_sdk/socket_mode/interval_runner.py
This pull request resolves #1003 by getting rid of all `Thread#setDaemon(bool)` usage in this repository. As the `setDaemon` method just does the following, it's safe enough to change the code:
```python
def setDaemon(self, daemonic):
self.daemon = daemonic
```
> Fix #1003 threading.Thread.setDaemon has been deprecated in Python 3.10

- slack_sdk/models/blocks/block_elements.py
Fix Url typo 
https://slack.dev/python-slack-sdk/api-docs/slack_sdk/models/blocks/block_elements.html#slack_sdk.models.blocks.block_elements.StaticSelectElement
> Fix url typo

- setup.py
> [#1009] fix mistake in webclient dependency version range

- slack_sdk/models/blocks/__init__.py
- slack_sdk/models/blocks/block_elements.py
- tests/slack_sdk/models/test_elements.py
This pull request adds `timepicker` block element support. As the element is still in beta, the specification can be changed until its GA release.
> Add timepicker block element support

- slack_sdk/models/views/__init__.py
- tests/data/view_modal_009.json
- tests/data/view_modal_010.json
- tests/slack_sdk/models/test_elements.py
- tests/slack_sdk/models/test_views.py
- tests/slack_sdk_fixture/view_modal_009.json
- tests/slack_sdk_fixture/view_modal_010.json
This pull request fixes #1021 by updating the `slack_sdk.models.views.View`'s constructor to convert a given `state` dict value to the `ViewState` class object. 
As all other properties in `View` class are already converted to class objects, changing this part would be a great improvement in terms of consistency. The changed property is still compatible with the current type hint - `Optional[Union[dict, ViewState]]`. We are going to apply this change in the next minor version - 3.6.
> Fix #1021 by updating View constructor to convert state as dict to class object

- slack_sdk/audit_logs/v1/logs.py
- tests/slack_sdk/audit_logs/test_response.py
This pull request adds missing properties in the Audit Logs API response classes.
> Update Audit Logs API response properties

- slack_sdk/models/blocks/block_elements.py
- tests/slack_sdk/models/test_elements.py
This pull request removes the confusing warning log messages in the constructors of Block Element base classes. As I mentioned at https://github.com/slackapi/python-slack-sdk/issues/1030#issuecomment-857634173, we generally don't recommend directly using the base classes such as `InteractiveElement` and `InputInteractiveElement` as these classes does not provide optimal ways to construct data for each block element. 
That said, displaying `!!! InputInteractiveElement's constructor args (initial_value) were ignored.If they should be supported by this library, report this issue to the project :bow: https://github.com/slackapi/python-slack-sdk/issues` for valid properties does not help us improve anything. Therefore, we will remove the warnings from the two classes.
> Remove confusing warning messages #1030

- README.md
Hi Slack developers! 
I noticed that there was a dead anchor link in the readme table of contents for RTM client documentation. I understand RTM is not especially promoted (in favor of socket mode) and a [prior PR understandably deleted the introductory RTM documentation from the readme](https://github.com/slackapi/python-slack-sdk/pull/807). However, it seems this lone dead link to to the now-deleted content was left behind. My PR removes the dead link so nobody is confused trying to click it, like I was. :)
Thanks!
> Remove Dead Link From Readme

- slack_sdk/socket_mode/interval_runner.py
`IntervalRunner.shutdown` method currently has to wait the full `interval_seconds` period due to using a `time.sleep` call. This change speeds up the shutdown by replacing it with a `threading.Event.wait` call.
> IntervalRunner: don't wait for `interval_seconds` on shutdown

- slack_sdk/socket_mode/builtin/internals.py
The current implementation uses hardcoded AF_INET (IPv4) family and a first DNS record for connection. This doesn't work in IPv6-only environments (via NAT64):
```
ERROR:slack_sdk.rtm_v2:Failed to establish a connection (session id: <STRIPPED>, error: [Errno -2] Name or service not known)
File "/usr/lib/python3/dist-packages/slack_sdk/socket_mode/builtin/connection.py", line 116, in connect
trace_enabled=self.trace_enabled,
File "/usr/lib/python3/dist-packages/slack_sdk/socket_mode/builtin/internals.py", line 123, in _establish_new_socket_connection
sock.connect((server_hostname, server_port))
File "/usr/lib/python3.6/ssl.py", line 1109, in connect
self._real_connect(addr, False)
File "/usr/lib/python3.6/ssl.py", line 1096, in _real_connect …
```
> socket_mode Connection: Add support for IPv6

- tutorial/03-responding-to-slack-events.md
- tutorial/PythOnBoardingBot/app.py
- tutorial/PythOnBoardingBot/requirements.txt
This PR updates the dependencies and handlers on the PythOnBoardingBot tutorial app sample `app.py` to use bolt-python instead of slackeventsapi as described in #1037. I've also updated the `**.md` documentation code snippets accordingly.
> Updates PythOnBoardingBot tutorial sample to use bolt-python

- integration_tests/web/test_issue_1053.py
- integration_tests/webhook/test_async_webhook.py
- integration_tests/webhook/test_webhook.py
- slack_sdk/web/async_client.py
- slack_sdk/web/client.py
- slack_sdk/web/legacy_client.py
This pull request fixes #1053 by eliminating the potential issues with a single comma-separated-value format data for a sequence type parameter (e.g., channel_ids, user_ids, etc.) in JSON request body. 
As far as I did tests with the mentioned endpoint, a single CSV format string value works even in the JSON request body. That being said, it should be much safer to switch the content-type from `application/json` to `application/x-www-form-urlencoded` in the long run. It is a proven way in the Java SDK and some others. 
We may want to eventually switch all the API methods to `application/x-www-form-urlencoded` for simplicity but it's out of this pull request's scope.
> Fix #1053 by changing request body format to params

- .gitignore
- slack_sdk/web/async_client.py
- slack_sdk/web/client.py
- slack_sdk/web/internal_utils.py
- slack_sdk/web/legacy_client.py
- slack_sdk/web/slack_response.py
- tests/slack_sdk/web/test_web_client_issue_1049.py
- tests/slack_sdk_fixture/web_response_admin_convo_pagination.json
- tests/slack_sdk_fixture/web_response_admin_convo_pagination_1.json
This pull request resolves #1049. While checking this issue, I found that the `__next__` iteration does not work if an API method use the JSON request body format. Thus, I've updated all other API methods that support pagination to use www-url-form-encoded request body.
> Fix #1049 by correcting request body format and next_cursor extraction

- integration_tests/samples/socket_mode/aiohttp_example.py
- slack_sdk/socket_mode/aiohttp/__init__.py
- slack_sdk/socket_mode/async_client.py
- slack_sdk/socket_mode/websockets/__init__.py
This pull request fixes #1065 by improving the internals of `AsyncSocketModeClient`. 
As described in the bug report, the reconnection occasionally may fail to properly replace the active WebSocket connection in the `connect_to_new_endpoint` method. 
If both the connection monitoring code and other code try to reconnect at the same time, a race condition issue can arise. In this case, the internal state `self.wss_uri` and `self.current_session` can be invalid (=stale). The invalid state is automatically repaired after a certain amount of time (say, less than 1 minute with the default setting) but the app can be unresponsive to any incoming requests until the recovery.
It's not so easy to reproduce the situation in unit tests but you can easily reproduce the situation by running the …
> Fix #1065 by having lock for async Socket Mode client reconnection

- slack_sdk/oauth/installation_store/sqlalchemy/__init__.py
Change the character length of the slack_bots.bot_token column 32 to 200
The bot_token column should be set to 200 characters, but it was set to 32 characters.
- [x ] **slack_sdk.oauth** (OAuth Flow Utilities)
> Fix the wrong column data size for bot_token in the built-in SQLAlchemy data model

- docs-src-v2/basic_usage.rst
- docs-src/web/index.rst
The API methods themselves are inconsistent about the spelling of
ratelimited vs rate_limited. chat.postMessage spells it
rate_limited. The API docs on rate limiting itself suggest using the
HTTP status code.
This updates the examples in the doc to use the status_code member of
Response objects, instead of looking in the returned JSON.
Closes #1073
- n/a: doc change only
> Update example code for rate limiting

- setup.py
- slack_sdk/errors/__init__.py
- slack_sdk/oauth/authorize_url_generator/__init__.py
- slack_sdk/oauth/installation_store/amazon_s3/__init__.py
- tests/slack_sdk/audit_logs/mock_web_api_server.py
- tests/slack_sdk/audit_logs/test_client.py
- tests/slack_sdk/oauth/installation_store/test_amazon_s3.py
- tests/slack_sdk/oauth/state_store/test_amazon_s3.py
This pull request adds more unit tests for better code coverage. Particularly, the following patterns are now covered:
* Error patterns in AuditLogsClient
* Amazon S3 backend OAuth stores (installation store & state store)
While writing the tests, I found a bug in AmazonS3InstallationStore's installation deletion methods. This pull request fixes the bug as well.
> Add more tests & fix a data deletion bug in AmazonS3InstallationStore

- slack_sdk/web/async_client.py
- slack_sdk/web/client.py
- slack_sdk/web/legacy_client.py
Tangentially related to https://github.com/slackapi/python-slack-sdk/issues/1018 , the main purpose was to potentially clean up the public interface for some `files_*` methods as well as expand and clarify my understanding of those API methods.
Based on the public API documentation available (like [the API documentation page for the `files_info` method](https://api.slack.com/methods/files.info)) I attempted to clean up the arguments for the `files_comments_delete`, `files_delete`, and `files_info` methods.
This is technically a breaking change. To keep this non-breaking, I could keep the `kwargs` in addition to defining the explicit method arguments.
> Add explicit arguments for files_info

- slack_sdk/audit_logs/v1/async_client.py
- slack_sdk/audit_logs/v1/client.py
- slack_sdk/http_retry/__init__.py
- slack_sdk/http_retry/builtin_async_handlers.py
- slack_sdk/scim/v1/async_client.py
- slack_sdk/scim/v1/client.py
- slack_sdk/web/async_base_client.py
- slack_sdk/web/base_client.py
- slack_sdk/webhook/async_client.py
- slack_sdk/webhook/client.py
- tests/slack_sdk/http_retry/test_builtins.py
- tests/slack_sdk_async/http_retry/test_builtins.py
This pull request removes all the globally mutable list objects from the pull request #1084 changes. If we have those, mutating the list of retry handlers can cause side effects to other API client instances in the same app.
> Improve #1084 by removing globally mutable lists

- slack_sdk/audit_logs/v1/async_client.py
- slack_sdk/audit_logs/v1/client.py
- slack_sdk/http_retry/builtin_handlers.py
- slack_sdk/scim/v1/async_client.py
- slack_sdk/scim/v1/client.py
- slack_sdk/web/async_base_client.py
- slack_sdk/web/base_client.py
- slack_sdk/webhook/async_client.py
- slack_sdk/webhook/client.py
- tests/slack_sdk/audit_logs/test_client_http_retry.py
- tests/slack_sdk/scim/test_client_http_retry.py
- tests/slack_sdk/web/test_web_client_http_retry.py
- tests/slack_sdk/web/test_web_client_http_retry_ratelimited.py
- tests/slack_sdk/webhook/test_webhook_http_retry.py
This pull request corrects a classic Python coding error 🤦 in #1084 #1092 . Passing mutable objects as default value for method arguments is a bad practice. The default value can be cached and can be shared among multiple instances. This pull request eliminates it by setting `None` to the arguments if nothing is passed.
> Improve #1092 #1084 by removing mutable method default arguments

- integration_tests/web/test_admin_rate_limit_retries.py
- slack_sdk/http_retry/builtin_async_handlers.py
- slack_sdk/http_retry/builtin_handlers.py
- slack_sdk/http_retry/response.py
- slack_sdk/web/async_internal_utils.py
- slack_sdk/web/base_client.py
- slack_sdk/web/slack_response.py
This pull request fixes a few bugs in #1084 about the built-in rate limited error handlers (sync/async)
> Improve #1084 to run rate limited error retry handler correctly

- slack_sdk/models/blocks/blocks.py
This pull request fixes #1095 by correcting a long-lived type hint error.
> Fix #1095 by correcting ContextBlock element type hint

- slack_sdk/models/blocks/basic_components.py
- tests/slack_sdk/models/test_options.py
This pull request fixes #1056 by changing the default type when a developer passes a str value for `text` when constructing `Option` values in a Block Kit select menu. As the current behavior using the constructor just does not work, I call this change a bug fix, not a breaking change.
> Fix #1056 by changing the default type for Option values

- slack/web/async_slack_response.py
- slack_sdk/web/async_slack_response.py
- slack_sdk/web/slack_response.py
- tests/slack_sdk/web/test_slack_response.py
- tests/slack_sdk_async/web/test_async_slack_response.py
This pull request fixes #1100 by improving `SlackResponse` and `AsyncSlackResponse`.
> Fix #1100 by improving the get/__getitem__ method behavior when response body is empty

- slack/web/async_slack_response.py
- slack_sdk/web/async_slack_response.py
- slack_sdk/web/slack_response.py
- tests/slack_sdk/web/test_slack_response.py
- tests/slack_sdk_async/web/test_async_slack_response.py
This pull request resolves #1102. Refer to the issue for details.
> Fix #1102 Add __contains__ method in slack_sdk.web.SlackResponse / AsyncSlackResponse

- slack_sdk/web/async_client.py
- slack_sdk/web/async_slack_response.py
- slack_sdk/web/client.py
- slack_sdk/web/internal_utils.py
- slack_sdk/web/legacy_client.py
- slack_sdk/web/slack_response.py
- tests/rtm/test_rtm_client_v2.py
- tests/slack_sdk/rtm_v2/test_rtm_v2.py
- tests/slack_sdk_async/web/test_async_web_client.py
- tests/slack_sdk_async/web/test_web_client_coverage.py
- tests/slack_sdk_async/web/test_web_client_issue_829.py
- tests/web/test_async_web_client.py
This pull request fixes #1018 by adding all the optional arguments in `WebClient`, `AsyncWebClient`, and `LegacyWebClient`.
> Fix #1018 Add optional arguments in WebClient methods

- integration_tests/samples/socket_mode/aiohttp_example.py
- slack_sdk/socket_mode/aiohttp/__init__.py
- slack_sdk/socket_mode/async_client.py
- slack_sdk/socket_mode/builtin/client.py
- slack_sdk/socket_mode/builtin/connection.py
- slack_sdk/socket_mode/websocket_client/__init__.py
- slack_sdk/socket_mode/websockets/__init__.py
- tests/slack_sdk_async/socket_mode/test_aiohttp.py
- tests/slack_sdk_async/socket_mode/test_interactions_aiohttp.py
This pull request fixes #1110 by improving the connection management of the AIOHTTP based Socket Mode client. I will add a few comments on the improvement.
> Fix #1110 Socket Mode disconnection issue with the aiohttp-based client

- slack_sdk/audit_logs/v1/logs.py
- tests/slack_sdk/audit_logs/test_response.py
This pull request adds message retention policy related fields to the `entity[].details` data. Also, improved the `Details` class constructor to accept both class data and dict value.
> Add missing properties in Audit Logs details data class

- slack_sdk/oauth/installation_store/file/__init__.py
We've got a question about the warning at https://github.com/slackapi/bolt-python/issues/464 and I found that we should not have the logs in warning level. It's just confusing and also we don't have the same log in warning level in other built-in implementations.
> Remove confusing warning from FileInstallationStore

- slack_sdk/socket_mode/aiohttp/__init__.py
- slack_sdk/socket_mode/builtin/client.py
- slack_sdk/socket_mode/builtin/connection.py
- slack_sdk/socket_mode/websocket_client/__init__.py
- slack_sdk/socket_mode/websockets/__init__.py
- tests/slack_sdk/socket_mode/test_interactions_builtin.py
- tests/slack_sdk/socket_mode/test_interactions_websocket_client.py
- tests/slack_sdk_async/socket_mode/test_interactions_aiohttp.py
- tests/slack_sdk_async/socket_mode/test_interactions_websockets.py
- tests/slack_sdk_async/socket_mode/test_websockets.py
This pull request improves the internals of built-in SocketModeClient implementations to properly handle the situations like https://github.com/slackapi/bolt-python/issues/461 I will add a few comments for reviewers.
> Improve the stability of SocketModeClient implementations

- .github/workflows/ci-build.yml
- slack_sdk/socket_mode/aiohttp/__init__.py
- slack_sdk/socket_mode/async_client.py
- slack_sdk/socket_mode/websockets/__init__.py
This pull request applies a few improvements to asyncio-based Socket Mode clients.
1. Add initial ping request to `connect()` method in AIOHTTP based client
This pull request adds a missing change in the pull request https://github.com/slackapi/python-slack-sdk/pull/1112
Like [the built-in client implementation does](https://github.com/slackapi/python-slack-sdk/blob/v3.11.0/slack_sdk/socket_mode/builtin/connection.py#L153), sending our own ping message to check if the connection is healthy can make the session check logic more accurate. If the connection is working, the client instance receives a new PONG message immediately and update the `self.last_ping_pong_time` with the timestamp of the latest trial.
This change can improve the situation described in this comment: …
> asyncio-based Socket Mode client improvements

- slack_sdk/socket_mode/websockets/__init__.py
This pull request resolves the build error issue in bolt-python project with python-slack-sdk v3.11.1: https://github.com/slackapi/bolt-python/actions/runs/1255825291
The error is caused by this change: https://github.com/slackapi/python-slack-sdk/pull/1117 More specifically, the following import is only compatible with websockets 9.x (the latest major series) while it's not with v8 or older ones.
>from websockets.legacy.client import WebSocketClientProtocol
This pull request corrects the import to make it compatible with all the websockets versions. For reference, the reason why bolt-python project detected the error is that the project has some tests for Sanic apps and the Sanic framework still requires websockets v8, not v9.
To prevent similar errors in our code, we may want to run …
> Change websockets imports to make it compatible with older versions

- slack_sdk/models/blocks/basic_components.py
- slack_sdk/models/blocks/block_elements.py
- slack_sdk/models/blocks/blocks.py
- tests/slack_sdk/models/test_elements.py
This pull request fixes #1127 by adding docstring to the Block Kit model classes. While working on this, I've noticed there are a few unusable arguments in some classes. I've removed them as well.
> Fix #1127 Add more docstrings to slack_sdk.models classes

- slack_sdk/socket_mode/aiohttp/__init__.py
This pull request fixes #1122 by improving the internals of the AIOHTTP-based Socket Mode client to be more consistent with the built-in client. Will add some context in line comments.
cc @eddyg
> Make the aiohttp-based SocketModeClient's debug logging more consistent with the built-in one (#1122)

- .github/workflows/pytype.yml
- slack_sdk/models/messages/__init__.py
- slack_sdk/oauth/installation_store/models/bot.py
- slack_sdk/oauth/installation_store/models/installation.py
- slack_sdk/oauth/state_store/sqlalchemy/__init__.py
This pull request upgrades pytype version to the latest.
> Upgrade pytype to 2021.11.18

- slack_sdk/models/basic_objects.py
- tests/slack_sdk/models/test_blocks.py
- tests/slack_sdk/models/test_elements.py
- tests/slack_sdk/models/test_objects.py
- tests/slack_sdk/models/test_views.py
Fixes #1131 
@seratch
Sorry for the delay.
I worked on the issue #1131.
I've confirmed the following.
- Passing Unit Tests
- Solving the problem in interactive mode
Thank you for checking!
> Fix #1131 Add the method to check equality in Block Kit model classes

- docs-src/socket-mode/index.rst
Fixes #1086 
Adds examples for Shortcuts and Modal submissions to the Socket Mode documentation.
I've run the synchronous version of the code and tested. For some reason the async code was failing with 
```
sys:1: RuntimeWarning: coroutine 'AsyncBaseSocketModeClient.process_messages' was never awaited
```
on
```python
asyncio.run(main())
```
I'm not to familiar with Python's aysnc, I also get this error with the version on `main` as well. It could also be an issue with me writing this on Windows. 
Let me know if you'd like any changes to the non code documentation, I made it a bit verbose so that a first time user should be able to follow the guide but I'm unsure if that's the target audience. 
I've also run `./scripts/docs.sh` and confirmed the webpage matched what I expected
> Fix 1086 add interactivity patterns in SocketModeClient docs

- slack_sdk/models/blocks/block_elements.py
- tests/slack_sdk/models/test_elements.py
This pull requset adds the new property "focus_on_load" to the Block Kit elements that support it.
> Add focus_on_load support in Block Kit

- integration_tests/audit_logs/test_pagination.py
- slack_sdk/audit_logs/v1/async_client.py
- slack_sdk/audit_logs/v1/client.py
- slack_sdk/audit_logs/v1/response.py
- tests/slack_sdk/audit_logs/mock_web_api_server.py
- tests/slack_sdk/audit_logs/test_client.py
- tests/slack_sdk_async/audit_logs/test_async_client.py
The Audit Logs API's /logs endpoint supports pagination in requests. Although developers can use `additional_query_params` as workaround now, we should have the `cursor` parameter in the method arguments.
> Add cursor parameter to Audit Logs API method

- integration_tests/web/test_issue_1143.py
- slack_sdk/audit_logs/v1/client.py
- slack_sdk/scim/v1/client.py
- slack_sdk/web/base_client.py
- slack_sdk/web/legacy_base_client.py
- slack_sdk/webhook/client.py
- tests/slack_sdk/scim/mock_web_api_server.py
- tests/slack_sdk/web/mock_web_api_server.py
- tests/slack_sdk/web/mock_web_api_server_http_retry.py
- tests/slack_sdk/web/test_web_client.py
- tests/slack_sdk/webhook/mock_web_api_server.py
- tests/slack_sdk_async/web/test_async_web_client.py
- tests/web/mock_web_api_server.py
- tests/web/test_async_web_client.py
- tests/web/test_web_client.py
This pull request fixes #1143, which is a regression bug since v3.12.0. For code consistency, I've updated all the clients but actually only `WebClient` had this issue.
> Fix #1143 Keep Retry-After header compatibility wit 2.x series

- .github/workflows/pytype.yml
- setup.py
This pull request upgrades the development tools -- code formatter and static code analyzer. No impact to the runtime behavior.
> Upgrade black, flake8, and pytype

- slack_sdk/web/async_client.py
- slack_sdk/web/client.py
- slack_sdk/web/legacy_client.py
- tests/slack_sdk_async/web/test_web_client_coverage.py
These are changes intended for beta release - as these are not GA, I have not yet included method unit tests.
* Adds Message Metadata field to chat.postMessage and chat.update methods
* Adds apps.notifications.subscriptions.* methods
* Adds a todo to implement tests once features are GA
>  [beta] Add support for Message Metadata and Subscribe in Slack API 

- README.md
This pull request resolves #1160. You can check the current state here: https://pypi.org/project/slack-sdk/ ("Getting started tutorial" section)
> Fix #1160 Links in README don't render properly on PyPi project page

- slack_sdk/models/blocks/block_elements.py
Fix #1170, TimePickerElement is missing in BlockElement.parse
> Fix #1170 Add TimePickerElement to BlockElement.parse

- integration_tests/samples/socket_mode/builtin_proxy_auth_example.py
- slack_sdk/socket_mode/builtin/internals.py
This pull request resolves #1169
> Fix #1169 by Proxy-Authorization header generation

- integration_tests/web/test_remote_file_replacement.py
- slack_sdk/web/async_client.py
- slack_sdk/web/client.py
- slack_sdk/web/legacy_client.py
This pull request resolves a bug on files.remote.* API support that affects v3.10, 3.11, 3.12, 3.13, 3.14 users. When we added all the optional parameter support in v3.10, the changes caused a regression bug on those API methods: https://github.com/slackapi/python-slack-sdk/pull/1099
> Fix a bug where some of the files.remote API parameters do not work since v3.10

- slack_sdk/socket_mode/builtin/client.py
- slack_sdk/socket_mode/builtin/connection.py
- slack_sdk/socket_mode/builtin/internals.py
- tests/slack_sdk/socket_mode/test_builtin.py
This PR should fix this bug: https://github.com/slackapi/python-slack-sdk/issues/1175
> Pass ssl_context from the web_client to the websocket

- integration_tests/web/test_bookmarks.py
- slack_sdk/web/async_client.py
- slack_sdk/web/client.py
- slack_sdk/web/legacy_client.py
- tests/slack_sdk_async/web/test_web_client_coverage.py
This PR adds support for the [add/edit/list/remove bookmark APIs](https://api.slack.com/methods?query=bookmarks).
This is my first PR adding support for new APIs, so reviews are appreciated. Maybe I missed some stuff? I.e. maybe integration tests? Not sure, would very much appreciate your guidance @seratch 🙇
> Add bookmarks.* API support

- slack_sdk/models/blocks/block_elements.py
- tests/slack_sdk/models/test_elements.py
This pull request resolves #1178
> Fix #1178 text type hint in LinkButtonElement does not accept PlainTextObject/dict

- slack_sdk/socket_mode/builtin/client.py
- slack_sdk/socket_mode/builtin/connection.py
This pull request fixes #1184 . Also, it changes other internal methods in the same way. As for the built-in internal modules, there is less benefit by displaying full stacktrace.
> Fix #1184 Add exception handling for socket mode - BlockingIOError: Resource temporarily unavailable

- slack_sdk/web/async_client.py
- slack_sdk/web/client.py
- slack_sdk/web/legacy_client.py
This pull request adds file_ids to chat.update parameters. Also, it fixes an existing bug in conversations_inviteShared method.
> Add file_ids to chat.update parameters

- slack_sdk/web/async_client.py
- slack_sdk/web/client.py
- slack_sdk/web/legacy_client.py
This pull request adds `domain` parameter to the [team.info](https://api.slack.com/methods/team.info) API method.
>The [team.info](https://api.slack.com/methods/team.info) parameter [domain](https://api.slack.com/methods/team.info#arg_domain) is now public. Query for your team's information by domain only when team is null.
>https://api.slack.com/changelog
> Add domain to team.info API parameters

- README.md
Removed broken/no-longer-relevant badges, added the info about migrating to v3 and updated name of v3 of the SDK on pypi. Also removed references to filing issues on github for support with v2.
WDYT @seratch ? If you approve, I think we should publish this commit to https://pypi.org/project/slackclient/. Once that is done, that would resolve #1197.
> V2 Readme updates: deprecation notice

- integration_tests/web/test_message_metadata.py
- slack_sdk/models/metadata/__init__.py
- slack_sdk/web/async_client.py
- slack_sdk/web/client.py
- slack_sdk/web/internal_utils.py
- slack_sdk/web/legacy_client.py
- tests/slack_sdk/web/test_web_client.py
This pull request adds message metadata support: https://api.slack.com/metadata
> Add message metadata support

- slack_sdk/models/basic_objects.py
- tests/slack_sdk/models/test_elements.py
This pull request resolves #1200
> Fix #1200 Model to_dict doesn't handle tuple sequences

- slack_sdk/web/async_client.py
- slack_sdk/web/client.py
- slack_sdk/web/internal_utils.py
- slack_sdk/web/legacy_client.py
- tests/slack_sdk/web/test_web_client_issue_891.py
- tests/slack_sdk/web/test_web_client_issue_971.py
- tests/slack_sdk_async/web/test_web_client_issue_891.py
- tests/web/test_web_client_issue_891.py
This follows the pattern in the solution converged on for https://github.com/slackapi/node-slack-sdk/issues/1476.
Wondering if there is an opportunity to DRY the tests up here, especially across the legacy vs. the regular synchronous client code. The tests seem to be a carbon copy. I don't really have a suggestion on how to improve that though, but maybe some more Python-y folks have ideas?
> Tweaking warnings related to missing accessibility fields `text` and `fallback`

- .github/workflows/pytype.yml
- setup.py
- slack_sdk/__init__.py
- slack_sdk/audit_logs/__init__.py
- slack_sdk/audit_logs/async_client.py
- slack_sdk/audit_logs/v1/logs.py
- slack_sdk/http_retry/__init__.py
- slack_sdk/http_retry/async_handler.py
- slack_sdk/models/__init__.py
- slack_sdk/models/blocks/__init__.py
- slack_sdk/models/blocks/basic_components.py
- slack_sdk/models/dialoags.py
- slack_sdk/models/dialogs/__init__.py
- slack_sdk/oauth/__init__.py
- slack_sdk/oauth/authorize_url_generator/__init__.py
- slack_sdk/oauth/installation_store/__init__.py
- slack_sdk/oauth/installation_store/models/__init__.py
- slack_sdk/oauth/installation_store/models/bot.py
- slack_sdk/oauth/state_store/__init__.py
- slack_sdk/oauth/token_rotation/__init__.py
- slack_sdk/rtm/v2/__init__.py
- slack_sdk/scim/__init__.py
- slack_sdk/scim/async_client.py
- slack_sdk/socket_mode/__init__.py
- slack_sdk/socket_mode/builtin/__init__.py
- slack_sdk/web/__init__.py
- slack_sdk/web/async_base_client.py
- slack_sdk/webhook/__init__.py
- slack_sdk/webhook/webhook_response.py
This pull request resolves #1209 by adding `__all__` to `__init__.py` files.
> Fix #1209 Add __all__ to __init__.py

- slack_sdk/web/async_client.py
- slack_sdk/web/client.py
- slack_sdk/web/legacy_client.py
- tests/slack_sdk_async/web/test_web_client_coverage.py
> Adding the auth_teams_list method

- slack_sdk/web/async_base_client.py
- slack_sdk/web/async_client.py
- slack_sdk/web/base_client.py
- slack_sdk/web/client.py
- slack_sdk/web/legacy_base_client.py
- slack_sdk/web/legacy_client.py
Parameters for client, async_client and legacy_client as well as their base classes. In particular focusing on documenting the proxy and ssl parameters (relates to #1214).
`web.client` expanded constructor parameter list that now includes `ssl`, `proxy` and `headers`:
`web.base_client` with instance variables now documented:
Similar changes for `web.async_client`, with the addition of `session` and `trust_env_in_session` parameters:
Similar to the above changes also exist in the legacy client, base legacy client, and base async client.
> Add more documentation around contructor parameters

- slack_sdk/models/blocks/block_elements.py
Fixes #1218. 
Though [API documentation](https://api.slack.com/reference/block-kit/block-elements#overflow) says a minimum of two options are required for the `overflow` menu, one is acceptable and works without issue. This PR updates the SDK's minimum number to match that.
> Fix #1218 - Reduce minimum number of overflow options

- .github/maintainers_guide.md
Updated the maintainers guide, this should help developer more clearly understand how to build the project and run the tests. This should also help push the project towards using a bash approach to building and running the test as implemented in the [bolt python project](https://github.com/slackapi/bolt-python).
What was done:
- Clarified how to initially install the dependencies and run all the unit tests
- Replaced the `python setup.py` commands with their corresponding bash script commands
- Added distinction between the 2 different types of documentation that can be generated
> Updated maintainer_guide

- .github/workflows/pytype.yml
This pull request upgrades pytype version to the latest.
> Upgrade pytype to the latest

- slack_sdk/oauth/token_rotation/async_rotator.py
Fix wrong return type annotation
> Fix return type annotation

- slack_sdk/models/blocks/block_elements.py
> Fix wrong type annotation

- slack_sdk/models/blocks/__init__.py
- slack_sdk/models/blocks/blocks.py
- tests/slack_sdk/models/test_blocks.py
This pull request resolves #1236
> Fix #1236 Add video block to Block Kit model classes

- slack_sdk/socket_mode/builtin/internals.py
Fix websocket handling code - test case at: https://github.com/mattbillenstein/slack-rtm_v2-recv-bug
From the README.txt there:
When listening on a websocket with the regular rtm_v2 lib using gevent, the
socket will after a time become unresponsive, and the cpu spin at 100%. This is
because the socket.recv() call doesn't return any data if the other end closed
the connection and the code gets into an infinite loop between _fetch and
receive because the error handling logic just returns an empty bytes object
- so the code whereever it is consuming data can't make progress.
Per the python3 sockets howto:
https://docs.python.org/3/howto/sockets.html:
"When a recv returns 0 bytes, it means the other side has closed (or is in
the process of closing) the connection. You will not receive any …
> rtm_v2 api spins in infinite loop under gevent

- slack_sdk/web/internal_utils.py
- tests/slack_sdk/web/test_internal_utils.py
Fix for `Tuple value for blocks argument does not work for Web API calls`
```py
blocks: Sequence[Block] = (
SectionBlock(text="foo"),
SectionBlock(text="bar"),
)
client.chat_postMessage(channel="#channel", blocks=blocks)
```
Resolves https://github.com/slackapi/python-slack-sdk/issues/1258
> Fix #1258 Tuple value for blocks argument does not work for Web API calls

- slack_sdk/web/async_base_client.py
Fixing the types for retry_handlers in the async client, according to docs and the code itself it should have been `AsyncRetryHandler` from the beggning
> fix retry_handlers type in AsyncBaseClient

- slack_sdk/models/views/__init__.py
New `TimePicker` element is not supported in the `ViewStateValue` class. See issue #1265
> add selected_time (timepicker) to ViewStateValue class

- slack_sdk/socket_mode/builtin/internals.py
This pull request tweaks an internal code in the built-in Socket Mode client. Since #1246 changes landed, we've received feedback from users that an active connection can be terminated unexpectedly.
```
File "/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/builtin/connection.py", line 305, in run_until_completion
received_messages: List[Tuple[Optional[FrameHeader], bytes]] = _receive_messages(
File "/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/builtin/internals.py", line 213, in _receive_messages
return _fetch_messages(
File "/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/builtin/internals.py", line 236, in _fetch_messages
remaining_bytes = receive()  # type: ignore
File …
```
> Adjust the logic added by #1246

- slack_sdk/socket_mode/builtin/internals.py
This pull request applies one more revert change to #1269
> Add more revert to #1269

- slack_sdk/web/internal_utils.py
Very simple PR to improve the clarity of the error message raised when 'content' is specified and it's not the correct type. (Feel free to edit as you see fit, or simply disregard if it's too minor.)
It is worth noting that the `else` case of this comparison (where neither `content` nor `file_uploads` is specified) is already handled [here](https://github.com/slackapi/python-slack-sdk/blob/main/slack_sdk/web/async_client.py#L3030-L3031) (for the async client) and [here](https://github.com/slackapi/python-slack-sdk/blob/main/slack_sdk/web/client.py#L3021-L3022) (regular).
> Improve clarity of 'content' error message for files_upload_v2

- slack_sdk/models/views/__init__.py
Simply fix type hint for `selected_option` parameter
> Fix selected_option type hint

- integration_tests/web/test_files_upload_v2.py
- slack_sdk/web/async_client.py
- slack_sdk/web/client.py
- slack_sdk/web/legacy_client.py
This pull request adds a new optional flag argument to files_upload_v2 method. When a developer passes full_file_info_required=False, the method skips fetching files.info response data for the uploaded files. Refer to https://github.com/slackapi/python-slack-sdk/issues/1277 for the context behind this change.
@srajiang I am thinking of adding the same flag to your Node SDK implementation. If you have any suggestions on better naming, I am happy to align for it.
> Add full_file_info_required to files_upload_v2 method

- .github/workflows/ci-build.yml
- setup.py
Python 3.11 is not available 🎉 This SDK should work with the latest version too
> Add Python 3.11 support

- slack_sdk/web/async_slack_response.py
- slack_sdk/web/slack_response.py
This is a ~~simple~~ somewhat complicated change that improves type handling when calling `.get()` on API responses.
For example, this line:
```python
if api_response and api_response.get("ok") and len(api_response.get("messages", [])):
```
currently generates this warning in Pyright:
```
Argument of type "Unknown | None" cannot be assigned to parameter "__obj" of type "Sized" in function "len"
  Type "Unknown | None" cannot be assigned to type "Sized"
    "__len__" is not present
```
This ~~simple~~ typing change alleviates this issue.
This is the first use of `TypeVar` in **slack_sdk** that I see... are there compatibility issues with older Python versions, perhaps? Opening this PR so this fix can at least be considered.
> Improve typing when using 'get' on an API response

- integration_tests/web/test_files_upload_v2.py
- slack_sdk/web/internal_utils.py
This pull request resolves #1292
> Fix #1292 files_upload_v2 does not work with io.BytesIO file parameters

- slack_sdk/web/async_client.py
- slack_sdk/web/client.py
- slack_sdk/web/internal_utils.py
- slack_sdk/web/legacy_client.py
- tests/slack_sdk/web/test_internal_utils.py
- tests/slack_sdk/web/test_web_client.py
- tests/slack_sdk_async/web/test_async_web_client.py
This pull request resolves #1297
> Fix #1297 Building user_auth_blocks with slack_sdk.models class objects for chat.unfurl API call fails

- slack_sdk/web/internal_utils.py
This pull request resolves #1302
> Fix #1302 by updating the warning logs in WebClient to be consistent with Node SDK

- slack_sdk/socket_mode/aiohttp/__init__.py
This pull request resolves #1304
> Fix #1304 ssl_context is not passed from async web_client to aiohttp socket client

- integration_tests/web/test_issue_1305.py
- slack_sdk/web/async_slack_response.py
This pull request resolves #1305
> Fix #1305 by fixing pagination with async for syntax

- slack_sdk/web/async_client.py
- slack_sdk/web/client.py
- slack_sdk/web/legacy_client.py
This pull request adds a new argument to emoji.list API. Refer to https://github.com/slackapi/java-slack-sdk/issues/821#issuecomment-1378235761 for its context.
> Add include_categories to emoji.list args

- setup.py
- slack_sdk/oauth/installation_store/sqlalchemy/__init__.py
- slack_sdk/oauth/state_store/sqlalchemy/__init__.py
This pull request resolves #1327. I've confirmed that the code works with both v1.4 and v2.0.
> Fix #1327 OAuth module: SQLAlchemy v2 compatibility

- integration_tests/samples/basic_usage/uploading_files.py
- slack_sdk/web/async_client.py
- slack_sdk/web/client.py
- slack_sdk/web/legacy_client.py
This pull request resolves #1342 . The root cause of the issue is miscoding in this SDK. The current implemenation of the v2 method internally passes "channel" parameter instead of "channel_id" parameter in `files.completeUploadExternal` API calls. Although "channel_id" is the correct one, the API server-side had been accepting both "channel" and "channel_id" until today. In the initial development of this v2 wrapper method on the SDK side, we overlooked the invalid parameter name due to the server-side behavior.
> Fix #1342 files_upload_v2 fails to share files in a channel

- integration_tests/web/test_issue_594.py
- slack_sdk/oauth/authorize_url_generator/__init__.py
- tests/slack_sdk/oauth/authorize_url_generator/test_generator.py
This pull request adds `team` parameter support to the authorize URL generators. Refer to the documents for details:
* https://api.slack.com/legacy/oauth#team_parameter
* https://api.slack.com/authentication/sign-in-with-slack#request
> Add team parameter support to the authorize URL generators

- .github/workflows/ci-build.yml
- setup.py
About 12 hours ago, codecov package was deleted from the PyPI registry as it's no longer supported. This pull request migrates the way to upload the coverage data to the service. In addition to the CI job setting change, I've added a new secret named CODECOV_TOKEN to this repository.
References:
* https://github.com/codecov/codecov-python
* https://community.codecov.com/t/codecov-yanked-from-pypi-all-versions/4259
> Migrate deprecated codecov to the latest recommended way

- slack_sdk/oauth/installation_store/sqlalchemy/__init__.py
This pull reqeust resolves a bug where the SQLAlchemy based installation store does not work properly for multile apps sharing a single database.
> Fix a bug where SQLAlchemy based InstallationStore is missing client_id in queries

- integration_tests/webhook/test_async_webhook.py
- integration_tests/webhook/test_webhook.py
- slack_sdk/webhook/async_client.py
- slack_sdk/webhook/client.py
As pointed out at https://github.com/slackapi/bolt-js/issues/1819, metadata argument must be supported when posting a message using response_url and incoming webhooks
> Add metadata support to Incoming Webhooks

- slack_sdk/oauth/state_store/sqlalchemy/__init__.py
Adds a `create_tables()` method to `slack_sdk.oauth.state_store.sqlalchemy.SQLAlchemyOAuthStateStore`, copied from `slack_sdk.oauth.installation_store.sqlalchemy.SQLAlchemyInstallationStore`.
It was / is missing when I tried using `SQLAlchemyOAuthStateStore` from the Python Slack SDK version 3.21.3.
I had to revert to the work-around of calling `SQLAlchemyOAuthStateStore.metadata.create_all(SQLAlchemyOAuthStateStore.engine)` directly.
Since `sqlalchemy.Metadata.create_all()` is idempotent, maybe a call to `create_tables()` could get added to `SQLAlchemyOAuthStateStore. __init__()` and `SQLAlchemyInstallationStore.__init__()`? Possibly behind a boolean flag parameter which would make it more obvious to 1st time users like me ;-) ?
LMK if you'd want me to add that to this PR.
> Add create_tables() to SQLAlchemyOAuthStateStore

- slack_sdk/web/async_client.py
- slack_sdk/web/client.py
- slack_sdk/web/legacy_client.py
This pull request adds a new feature to team.accessLogs API method. See https://api.slack.com/changelog for details.
See also: https://github.com/slackapi/java-slack-sdk/pull/1160
> Add cursor based pagination to team.accessLogs

- slack_sdk/http_retry/builtin_async_handlers.py
- slack_sdk/http_retry/builtin_handlers.py
This pull request resolves https://github.com/slackapi/python-slack-sdk/issues/1364
> Add built in server error retry handlers

- slack_sdk/http_retry/builtin_handlers.py
Bugfix for https://github.com/slackapi/python-slack-sdk/pull/1367
> fix[builtin_handlers]: ServerErrorRetryHandler, renaming _can_retry_async -> _can_retry

- .github/workflows/ci-build.yml
- .github/workflows/pytype.yml
This PR bumps the versions of the [actions/checkout](https://github.com/actions/checkout) and [actions/setup-python](https://github.com/actions/setup-python) actions to the latest versions to remove the warning of using a deprecated Node version in GitHub Actions.
I am hoping that this might fix the unresolved "Waiting for status to be reported" status from the codecov step too :eyes:
> Update GitHub Action steps to use Node 16

- slack_sdk/models/blocks/blocks.py
- tests/slack_sdk/models/test_blocks.py
This pull request resolves #1369
> Fix #1369 ImageBlock title parsing defaults to incorrect behaviour when given a string

- .github/workflows/ci-build.yml
- .github/workflows/pytype.yml
This PR builds upon the changes in #1375 and replaces the codecov-uploader with the codecov-action. All in the hope of having coverage stats report successfully.
> Use codecov/codecov-action@v3 to upload code coverage

- slack_sdk/socket_mode/websocket_client/__init__.py
- tests/slack_sdk/socket_mode/test_interactions_websocket_client.py
This pull request resolves #1379 
The `_monitor_current_session` method in the same class already checks the existence of the `sock` property. So, having the same logic should be consistent and safe enough.
> Fix #1379 websocket-client socket mode client doesn't handle reconnects properly

- slack_sdk/models/blocks/blocks.py
- slack_sdk/web/async_base_client.py
- slack_sdk/web/base_client.py
- slack_sdk/web/deprecation.py
- slack_sdk/web/legacy_base_client.py
- tests/slack_sdk/web/test_web_client_stars_deprecation.py
see also: https://api.slack.com/changelog/2023-07-its-later-already-for-stars-and-reminders
(Describe the goal of this PR. Mention any related issue numbers)
> Mark stars.* API methods as deprecated

- setup.py
Based on code searches and running the test suite, AFAICT this dependency is vestigial.
> setup.py: remove unused `databases` dependency

- slack_sdk/models/blocks/basic_components.py
- slack_sdk/models/blocks/block_elements.py
- tests/slack_sdk/models/test_elements.py
- tests/slack_sdk/models/test_objects.py
This pull request adds a new block element (https://api.slack.com/reference/block-kit/block-elements#workflow_button) to slack_sdk.models package.
> Add workflow_button block element

- README.md
This PR updates the example in the README to recommend using `files_upload_v2` for uploading files to avoid warnings raised by the current `files_upload` method.
Unsure if linking to the release notes for `files_upload_v2` is alright (instead of API documentation) since there are multiple API methods being called now. These release notes do a great job of documenting this method though, so I think this might be helpful!
> Recommend using the `files_upload_v2` method for uploading files

- slack_sdk/models/blocks/__init__.py
- slack_sdk/models/blocks/block_elements.py
- tests/slack_sdk/models/test_elements.py
This pull request adds RichTextInputElement to slack_sdk.models utilities.
references:
* https://api.slack.com/reference/block-kit/block-elements#rich_text_input
> Add RichTextInputElement to slack_sdk.models

- integration_tests/web/test_files_upload_v2.py
- slack_sdk/web/async_client.py
- slack_sdk/web/client.py
- slack_sdk/web/internal_utils.py
- slack_sdk/web/legacy_client.py
This pull request updates the internals of `files_upload_v2` method to eliminate files.info API calls, which are no longer necessary because the server-side now returns the same metadata as part of `files.completeUploadExternal` API responses.
> Update files.upload v2 method in correspondence with server-side changes

- slack_sdk/web/internal_utils.py
- tests/slack_sdk/web/test_internal_utils.py
This pull request improves the internal logic to extract next_cursor from Slack Web API response. As of today, all the public APIs return empty string (meaning `""`) when the API does not have its next page. With that being said, the platform may add some inconsistent behavior in the future. Thus, just in case, we want to make this SDK code even more robust for such scenario. Refer to #1407 for its context.
> Make next_cursor extraction logic even more robust (ref #1407)

- slack_sdk/web/async_client.py
- slack_sdk/web/client.py
- slack_sdk/web/legacy_client.py
This pull request adds two newly added options to https://api.slack.com/methods/admin.users.list
> Add new arguments to admin.users.list API method

- README.md
- slack_sdk/web/base_client.py
- tests/slack_sdk/web/test_web_client.py
- tests/slack_sdk/web/test_web_client_http_retry_server_error.py
- tests/slack_sdk/web/test_web_client_issue_829.py
This pull request resolves #1421, also updated unit tests and README.
> Fix #1421 Update SlackApiError exception handling for web client

- slack_sdk/models/blocks/block_elements.py
- tests/slack_sdk/models/test_elements.py
This pull request resolves #1424
> Fix #1424 Add file input block element support

- integration_tests/web/test_app_manifest.py
- slack_sdk/web/async_client.py
- slack_sdk/web/client.py
- slack_sdk/web/legacy_client.py
- tests/slack_sdk_async/web/test_web_client_coverage.py
This pull request resolves #1427
> Fix #1427 Add apps.manifest.* & tooling.tokens.rotate API support

- slack_sdk/models/blocks/__init__.py
- slack_sdk/models/blocks/block_elements.py
- slack_sdk/models/blocks/blocks.py
- tests/slack_sdk/models/test_blocks.py
This pull request resolves #1428
> Fix #1428 Add rich_text classes to slack_sdk.models module

- integration_tests/web/test_admin_conversations_restrictAccess.py
- integration_tests/web/test_calls.py
- slack_sdk/web/async_client.py
- slack_sdk/web/client.py
- slack_sdk/web/legacy_client.py
- tests/slack_sdk_async/web/test_web_client_coverage.py
This pull request adds two endpoints, which will be coming soon, to WebClient family. Developers can use these APIs along with https://github.com/slackapi/bolt-python/pull/986
> Add functions.completeSuccess/Error APIs for remote functions

- slack_sdk/models/blocks/blocks.py
- tests/slack_sdk/models/test_blocks.py
This pull request adds a missing change in https://github.com/slackapi/python-slack-sdk/pull/1431
(reported at https://github.com/slackapi/python-slack-sdk/pull/1431#discussion_r1402730142)
> Add RichTextBlock to Block.parse() targets

- .github/workflows/ci-build.yml
- pytest.ini
- setup.py
- slack_sdk/oauth/installation_store/internals.py
- slack_sdk/oauth/installation_store/models/bot.py
- slack_sdk/oauth/installation_store/models/installation.py
- tests/slack_sdk/oauth/installation_store/test_internals.py
- tests/slack_sdk_async/socket_mode/test_interactions_websockets.py
Hello,
I believe it would be nice to ensure support for Python 3.12 and PyPy,
so I'd like to suggest changes that:
* enable testing for Python 3.12 and PyPy 3.10 on CI
* resolve/suppress some warnings
* update [classifiers](https://pypi.org/classifiers/) at `setup.py`
* bump `pytest` to 7.x
* update constraints for `flake8` to allow `pip` do its job and resolve [compatibility issues](https://github.com/Jamim/python-slack-sdk/actions/runs/7023401877/job/19109825126#step:5:87)
* refactor timestamp conversion logic in order to resolve a bunch of [E721](https://www.flake8rules.com/rules/E721.html) `flake8` errors
* fix some regexps with [invalid escaping](https://github.com/Jamim/python-slack-sdk/actions/runs/7023401877/job/19109825126#step:5:14) at `setup.py`
* fix spontaneous failures of …
> Enable testing for Python 3.12 and PyPy 3.10 on CI

- slack_sdk/web/async_client.py
- slack_sdk/web/client.py
- slack_sdk/web/legacy_client.py
Not released yet, but soon!
Adds a new `force` parameter that will be imminently available in the `conversations.invite` API method.
> Add new `force` argument to `conversations.invite` API method.

- slack_sdk/socket_mode/aiohttp/__init__.py
`__init__.py` redeclared type before using it, leading to an error when the exception in receive_messages was reached.
> Stop from re-declaring 'type' keyword

- scripts/run_integration_tests.sh
- scripts/run_unit_tests.sh
- scripts/run_validation.sh
Hello,
The _Maintainers Guide_ [says that](https://github.com/slackapi/python-slack-sdk/blob/main/.github/maintainers_guide.md?plain=1#L78-L82) no formatter nor code analyzer is involved when you run unit tests, so I suppose `black` was added by mistake and should be removed.
Also, using [set -e](https://git.savannah.gnu.org/cgit/bash.git/tree/builtins/set.def#n64) allows you to avoid chaining of commands.
I'd like to suggest changes that:
* remove `black` from `run_*_tests.sh` scripts
* add `set -e` to unchain commands in scripts
* simplify handling of a test target
Best regards!
> Update run_*.sh scripts

- .github/workflows/ci-build.yml
- requirements/testing.txt
- scripts/run_validation.sh
- setup.py
- tests/slack_sdk/socket_mode/mock_socket_mode_server.py
- tests/slack_sdk/socket_mode/test_interactions_builtin.py
- tests/slack_sdk/socket_mode/test_interactions_websocket_client.py
- tests/slack_sdk_async/socket_mode/test_interactions_aiohttp.py
- tests/slack_sdk_async/socket_mode/test_interactions_websockets.py
Hello @seratch,
I hope you may find this PR useful.
`Flask-Sockets` [is deprecated](https://github.com/heroku-python/flask-sockets/issues/85) and it won't receive any fixes in the future, so it seems reasonable to replace it with some up-to-date library.
`aiohttp` has been chosen since it was already presented as an optional requirement.
These changes also:
* move format checking for tests from `run_validation.sh` to `setup.py`
* remove duplicated dependency installations from `setup.py`
* add a `codegen` step on CI
* force colors on CI
Best regards!
> Replace Flask-Sockets with aiohttp for testing

- docs/api-docs/slack_sdk/index.html
- docs/api-docs/slack_sdk/web/async_client.html
- docs/api-docs/slack_sdk/web/client.html
- docs/api-docs/slack_sdk/web/index.html
- docs/api-docs/slack_sdk/web/legacy_client.html
- slack_sdk/web/async_client.py
- slack_sdk/web/client.py
- slack_sdk/web/legacy_client.py
Fix a broken link related to the documentation of modals.
> fixed broken link related to documenation of modals.

- slack_sdk/socket_mode/aiohttp/__init__.py
- tests/slack_sdk/socket_mode/mock_socket_mode_server.py
- tests/slack_sdk/socket_mode/mock_web_api_server.py
- tests/slack_sdk/socket_mode/test_builtin.py
- tests/slack_sdk_async/socket_mode/test_aiohttp.py
- tests/slack_sdk_async/socket_mode/test_interactions_aiohttp.py
- tests/slack_sdk_async/socket_mode/test_websockets.py
- Fix the problem of monitor dies if an exception raised during reconnect before monitor created.
- Add a unit test `test_interactions_with_disconnection` for Slack server side request to disconnect.
> fix #1446: monitor dies when exceptions raised before monitor created.

- README.md
The goal of this PR is to add the a downloads badge to the readme, the title and badges were also centered.
look at [this fork](https://github.com/WilliamBergamin/python-slack-sdk/tree/improve-readme) to see the rendered version
> feat: add download badge in readme

- pyproject.toml
This PR aims to fix #1455 by exposing the dependencies  found in `requirements/optional.txt`
I've deployed these changes to https://test.pypi.org/project/slack-sdk/3.26.3a0/
You can test them out by executing `pip3 install -i https://test.pypi.org/simple/ 'slack-sdk[optional]==3.26.3a0'` 
NOTE: the install will fail since not all of the dependencies in `requirements/optional.txt` are in test.pypi.org
> fix: optional dependency install

- slack_sdk/models/blocks/basic_components.py
- slack_sdk/models/blocks/block_elements.py
- slack_sdk/models/blocks/blocks.py
- tests/slack_sdk/models/test_blocks.py
- tests/slack_sdk/models/test_elements.py
This pull request resolves #1450
> Fix #1450 slack_file in image block/element

- slack_sdk/socket_mode/aiohttp/__init__.py
This pull request resolvers #1458
> Fix #1458 internal error within aiohttp-based socket mode client

- requirements/testing.txt
- tests/slack_sdk/oauth/installation_store/test_amazon_s3.py
- tests/slack_sdk/oauth/state_store/test_amazon_s3.py
To stop testing with old versions of moto, unpin it from version 3, to the latest, and also change the test cases to cope with the new changes.
> Unpin moto, and support moto 5.0 changes

- slack_sdk/socket_mode/websocket_client/__init__.py
This pull request resolves #1462
> Fix #1462 websocket_client-based SocketModeClient does not reconnect after a DNS outage

- .github/dependabot.yml
Since all dependencies in this project are optional or for testing, I suggest to change dependabot checks to monthly instead of weekly
> fix: dependabot schedule

- requirements/optional.txt
- requirements/testing.txt
Dependabot does not seem to honor the python version specifier https://github.com/dependabot/dependabot-core/issues/8346
In bolt for python we specify a version range instead of assigning a specific dependency version for each python version, this PR aims to do this
Reference: [bolt-python/adapter_testing.txt](https://github.com/slackapi/bolt-python/blob/main/requirements/adapter_testing.txt)
> fix: simplify dependency specifiers for dependabot

- .github/workflows/ci-build.yml
- tests/slack_sdk/socket_mode/test_interactions_builtin.py
- tests/slack_sdk/socket_mode/test_interactions_websocket_client.py
- tests/slack_sdk_async/socket_mode/test_interactions_aiohttp.py
- tests/slack_sdk_async/socket_mode/test_interactions_websockets.py
The latest minor version of pytest (8.2), which was released a few days ago, affects some of the tests that this project has. So, this pull request locks the version to its previous for now.
> Omit two websocket_client/websockets tests due to their instability on GitHub Actions

- slack_sdk/models/blocks/block_elements.py
- tests/slack_sdk/models/test_blocks.py
This pull request resolves #1468
> fix `RichTextElement.elements` items are never promoted to a proper Python object type

- setup.py
- slack_sdk/web/async_base_client.py
- slack_sdk/web/async_client.py
- slack_sdk/web/async_internal_utils.py
- slack_sdk/web/base_client.py
- slack_sdk/web/client.py
- slack_sdk/web/file_upload_v2_result.py
- slack_sdk/web/internal_utils.py
- slack_sdk/web/legacy_base_client.py
- slack_sdk/web/legacy_client.py
This pull request resolves #1496
> Fix #1496 Async client uses blocking call when uploading file with v2

- slack_sdk/web/deprecation.py
- tests/slack_sdk/web/test_web_client_workflow_step_deprecation.py
This PR aims to add a deprecation warning for methods that related to [legacy workflows](https://api.slack.com/changelog/2023-08-workflow-steps-from-apps-step-back)
Here is an example of the warning
```log
UserWarning: workflows.updateStep is deprecated. For more info, go to https://api.slack.com/changelog/2023-08-workflow-steps-from-apps-step-back
```
> fix: Add deprecation warnings to Steps from Apps methods

- integration_tests/web/test_canvases.py
- slack_sdk/web/async_client.py
- slack_sdk/web/client.py
- slack_sdk/web/legacy_client.py
- tests/slack_sdk_async/web/test_web_client_coverage.py
This pull request adds the following new APIs to slack-api-client library:
* canvases.access.delete
* canvases.access.set
* canvases.create
* canvases.delete
* canvases.edit
* canvases.sections.lookup
* conversations.canvases.create
* users.discoverableContacts.lookup
> Add canvases APIs and users.discoverableContacts.lookup API

- README.md
This PR updates the readme to follow the same pattern found in `bolt`, the `sdk` and the `hooks` projects
[Preview](https://github.com/WilliamBergamin/python-slack-sdk/blob/update-readme/README.md)
> chore: align README pattern

- docs/api-docs/slack_sdk/index.html
- docs/api-docs/slack_sdk/oauth/installation_store/file/index.html
- docs/api-docs/slack_sdk/oauth/installation_store/index.html
- docs/api-docs/slack_sdk/oauth/state_store/file/index.html
- docs/api-docs/slack_sdk/oauth/state_store/index.html
- docs/api-docs/slack_sdk/web/async_client.html
- docs/api-docs/slack_sdk/web/client.html
- docs/api-docs/slack_sdk/web/index.html
- docs/api-docs/slack_sdk/web/legacy_client.html
- slack_sdk/version.py
> chore(release): 3.30.0

- .github/maintainers_guide.md
- .github/pull_request_template.md
This PR improve the release instructions and updates the pull request template
> chore: small maintainer guidelines 

- .github/pull_request_template.md
- docs/content/audit-logs.md
- docs/content/index.md
- docs/content/installation.md
- docs/content/legacy/auth.md
- docs/content/legacy/basic_usage.md
- docs/content/legacy/changelog.md
- docs/content/legacy/conversations.md
- docs/content/legacy/faq.md
- docs/content/legacy/index.md
- docs/content/legacy/real_time_messaging.md
- docs/content/oauth.md
- docs/content/rtm.md
- docs/content/scim.md
- docs/content/socket-mode.md
- docs/content/v3-migration.md
- docs/content/web.md
- docs/content/webhook.md
The classic code practice of breaking lines at x characters long messed up the unfurls. Removed the line breaks
Oh I just noticed the path in this template still says `/docs-src` so I changed it to `/docs` in this PR too
You can run it locally to see that it works, but it works. You can't test unfurls locally though
> Docs: remove line breaks in md intros for unfurls

- docs/static/api-docs/slack_sdk/index.html
- docs/static/api-docs/slack_sdk/models/blocks/block_elements.html
- docs/static/api-docs/slack_sdk/models/blocks/index.html
- docs/static/api-docs/slack_sdk/web/async_client.html
- docs/static/api-docs/slack_sdk/web/client.html
- docs/static/api-docs/slack_sdk/web/index.html
- docs/static/api-docs/slack_sdk/web/legacy_client.html
- slack_sdk/version.py
> version 3.32.0

- slack_sdk/models/blocks/block_elements.py
Fix the type.
If passing an actual `str`:
```
slack_sdk.errors.SlackApiError: The request to the Slack API failed. (url: https://slack.com/api/chat.postMessage, status: 200)
The server responded with: {'ok': False, 'error': 'invalid_blocks', 'errors': ['must provide an integer [json-pointer:/blocks/1/elements/0/elements/1/timestamp]'], 'response_metadata': {'messages': ['[ERROR] must provide an integer [json-pointer:/blocks/1/elements/0/elements/1/timestamp]']}}
```
> Fix RichTextElementParts.Date.timestamp to be an int

- README.md
- docs/README.md
- docs/content/index.md
- docs/content/legacy/changelog.md
- docs/content/legacy/index.md
- docs/content/oauth.md
- docs/content/scim.md
- docs/content/v3-migration.md
- docs/content/web.md
- docs/docusaurus.config.js
- docs/sidebars.js
Switching from slack.dev to tools.slack.dev
It's just a name swap! Can't fully test until deployment though 🤞
> Docs: new URL (HOLD)

- slack_sdk/models/blocks/block_elements.py
- tests/slack_sdk/models/test_elements.py
This pull request resolves #1517
> Fix #1517 initial_value for RichTextInputElement should also accept type RichTextBlock

- slack_sdk/models/basic_objects.py
- tests/slack_sdk/models/test_blocks.py
This pull request resolves a bug where a few rich_text block element representation in slack_sdk.models package does not an empty value for "element" property. An empty array must be allowed for the property while most other properties in Block Kid do not allow empty arrays.
> Enable rich_text_* elements to have an empty 'elements' property

- slack_sdk/socket_mode/aiohttp/__init__.py
Fixes https://github.com/slackapi/python-slack-sdk/issues/1592
> Fix #1592 by encoding aiohttp client session pings

- slack_sdk/web/async_base_client.py
- slack_sdk/web/base_client.py
- slack_sdk/web/legacy_base_client.py
- tests/slack_sdk/web/test_web_client.py
This PR addresses issue #1541 by ensuring that a trailing `/` is appended to the end of the URL in base_url if it is not already provided. This change ensures consistent URL formatting and avoids potential issues caused by missing trailing slashes in API calls.
1. Unit Tests
Run the following command to ensure all relevant test cases pass:
```bash
./scripts/run_unit_tests.sh tests/slack_sdk/web/test_web_client.py
```
2. Manual Testing
- Use a custom `base_url` without a trailing `/` in a sample implementation. Confirm that the URL is automatically appended with a `/ `during API calls.
- Use a `base_url` with a trailing `/` and verify that no additional `/` is appended.
- [x ] **slack_sdk.web.WebClient (sync/async)** (Web API client)
- [x ] I've read and understood the [Contributing …
> add trailing slash to the end of the url

- slack_sdk/socket_mode/websockets/__init__.py
- tests/slack_sdk_async/socket_mode/test_interactions_websockets.py
This PR aims to resolve #1612
Followed [Upgrade to the new asyncio implementation](https://websockets.readthedocs.io/en/stable/howto/upgrade.html) to come up with these changes. Socket mode uses `websockets.WebSocketClientProtocol` in its implementation, this class was replaced with [websockets.asyncio.client.ClientConnection](https://websockets.readthedocs.io/en/stable/reference/asyncio/client.html#websockets.asyncio.client.ClientConnection). 
These interfaces are very similar but `ClientConnection` lacks the `closed` method found in `WebSocketClientProtocol`. As a workaround proposed to use `.close_code is not None` to determine if a session is closed or in the process of being closed. Close code is defined in [RFC 6455 sec 7.1.5](https://datatracker.ietf.org/doc/html/rfc6455.html#sectio …
> fix: 'ClientConnection' object has no attribute 'closed'

- tests/slack_sdk/socket_mode/mock_socket_mode_server.py
- tests/slack_sdk/socket_mode/test_interactions_builtin.py
- tests/slack_sdk/socket_mode/test_interactions_websocket_client.py
- tests/slack_sdk_async/socket_mode/test_interactions_aiohttp.py
- tests/slack_sdk_async/socket_mode/test_interactions_websockets.py
This PR aims to improve flaky tests in our CI pipeline and consolidate the mock socket mode clients found in this project
Ran the Ci pipeline a few times did not observe any flaking tests
> chore: improve flaky tests

- .github/workflows/ci-build.yml
- pyproject.toml
This PR aims to add official support for python 3.13
Unit tests pass locally 🟢 
Manually tested basic apps 🟢
> chore: support python 3.13

- .github/workflows/ci-build.yml
- tests/helpers.py
- tests/slack_sdk/socket_mode/test_interactions_websocket_client.py
#1023 disabled units that were found to be unstable in our CI pipeline, #1615 improved the stability of these tests, this PR aims to reenable these unit tests in our CI pipeline
Test in CI pipeline
> build: enable tests that are now stable

- slack_sdk/socket_mode/aiohttp/__init__.py
Try to avoid internal exceptions from aiohttp in `message_data`
Fix for #1622 
I couldn't figure out a way to unit test for this, and the integration tests were over my head.
> Additional check for exceptions from aiohttp

- slack_sdk/models/blocks/blocks.py
- tests/slack_sdk/models/test_blocks.py
This pull request resolves #1611
> Fix #1611 Add expand attribute to SectionBlock

- slack_sdk/oauth/installation_store/models/bot.py
- slack_sdk/oauth/installation_store/models/installation.py
- slack_sdk/oauth/token_rotation/async_rotator.py
- slack_sdk/oauth/token_rotation/rotator.py
- tests/slack_sdk/oauth/installation_store/test_models.py
- tests/slack_sdk/oauth/token_rotation/test_token_rotator.py
- tests/slack_sdk_async/oauth/token_rotation/test_token_rotator.py
This pull request resolves #1636
> Fix #1636 Custom Values passed into correctly into Bot/Installation class when cloned during token rotation

- requirements/testing.txt
- slack_sdk/oauth/installation_store/sqlalchemy/__init__.py
- slack_sdk/oauth/state_store/sqlalchemy/__init__.py
- tests/helpers.py
- tests/slack_sdk/oauth/installation_store/test_async_sqlalchemy.py
- tests/slack_sdk/oauth/state_store/test_async_sqlalchemy.py
Add support for Asyncio SQLAlchemy Installation and StateStore
> feat: #1276 add Asyncio SQLAlchemy support

- slack_sdk/web/async_client.py
- slack_sdk/web/client.py
- slack_sdk/web/legacy_client.py
This pull request adds the newly added "channels" parameter to files.upload v2 method and its underlying API endpoint
See also: https://github.com/slackapi/java-slack-sdk/pull/1427
> Add channels param to files.upload v2 method

- slack_sdk/oauth/state_utils/__init__.py
Fixes https://github.com/slackapi/python-slack-sdk/issues/1647.
Note that the second replace("'", "") was not needed in my case - but to future proof for any quoting issues
Follow the flow in https://github.com/slackapi/python-slack-sdk/issues/1647
> Remove quotes from cookie value in OAuthStateUtils

- slack_sdk/models/blocks/basic_components.py
According to the docs, this property accepts a maximum length of 150 chars whereas the SDK enforces 75.
- https://api.slack.com/reference/block-kit/composition-objects#option
> `value`: (String) A unique string value that will be passed to your app when this option is chosen. Maximum length for this field is 150 characters.
Without this fix, we can get validation errors:
```
slack_sdk.errors.SlackObjectFormationError: value attribute cannot exceed 75 characters
```
> Fix max length for static option values

- pyproject.toml
The `pytest-runner` package has been deprecated upstream for some time, and the project is now archived:
https://github.com/pytest-dev/pytest-runner/tree/v6.0.1?tab=readme-ov-file#deprecation-notice
Furthermore, the "setup.py test" command was removed in setuptools 72: https://github.com/pypa/setuptools/blob/v75.8.0/NEWS.rst#v7200
This does not affect running the tests with pytest.
Removes the dependency on the deprecated `pytest-runner` package, which – since this project does not use the deprecated/removed `setup.py test` for running tests and does not use the deprecated `tests_require` for expressing test dependencies – was no longer doing anything useful anyway.
Run the tests, in any of the usual ways, and observe that everything still works.
Consult the [linked deprecation notice for …
> Remove pytest-runner from build-system.requires

- docs/content/tutorial/uploading-files.md
This aims to fix #1669, by updating the docs to use `channel` argument rather then `channel_id` this is what the [source code expects](https://github.com/slackapi/python-slack-sdk/blob/897449acec0a810dd4a460008d22554ffcdcdd46/slack_sdk/web/client.py#L3749C9-L3749C16)
> fix: `channel_id` instead of `channel` in `files_upload_v2` documentation

- .github/maintainers_guide.md
This PR copies the steps for using `scripts/build_pypi_package.sh` from `slack_bolt` - [reference](https://github.com/slackapi/bolt-python/blob/main/.github/maintainers_guide.md#develop-locally) - to this `maintainers_guide.md` for fast reference 📚 
The updated steps were used to test that the build script packages the `.whl`!
> docs: include packaging script steps in the maintainers guide

- integration_tests/web/test_files_upload_v2.py
- slack_sdk/web/async_client.py
- slack_sdk/web/client.py
- slack_sdk/web/internal_utils.py
- slack_sdk/web/legacy_client.py
- tests/slack_sdk/web/test_internal_utils.py
Allow passing Path objects into file upload functions.
Attempt to pass a `Path` object to one of the file upload functions that takes a string path. Also pass a string path to ensure there are no regressions.
I did get S3 test failures with the latter (without my change), FYI.
> Support pathlike objects in upload util

- .github/workflows/ci-build.yml
- .gitignore
This PR is inspired by https://github.com/slackapi/node-slack-sdk/pull/2178
It updates the CI pipeline to publish the test results to codcov and provide some [neat reporting details](https://docs.codecov.com/docs/test-analytics#reporting)
> health: publish test results to code cov

- .github/workflows/ci-build.yml
The Ubuntu 20.04 Actions runner image will begin deprecation on 2025-02-01 and will be fully unsupported by 2025-04-15 (https://github.com/actions/runner-images/issues/11101). The next [available image](https://github.com/actions/runner-images?tab=readme-ov-file#available-images) is [Ubuntu 22.04](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md), but it does not support Python 3.6.
```
Error: The version '3.6' with architecture 'x64' was not found for Ubuntu 22.04.
```
The project is in the process of dropping support for `python 3.6` until this is done the team will need to manually validate compatibility with `python 3.6`
Steps:
1. `pyenv shell 3.6.15`
2. `python --version` -> `Python 3.6.15`
3. `python -m venv env_3.6.15`
4. `source …
> chore: remove 3.6 CI support

- .github/workflows/ci-build.yml
- .github/workflows/docs-deploy.yml
- .github/workflows/mypy.yml
- .github/workflows/triage-issues.yml
This PR uses the wonderful [`zizmor`](https://github.com/zizmorcore/zizmor) tool to audit our own workflows and [`pinact`](https://github.com/suzuki-shunsuke/pinact) for pinned versioning 👾 
🔍 Watching CI for these results! But I hope nothing has changed.
A similar audit can be performed with the `zizmor` tool:
```sh
$ zizmor .
...
No findings to report. Good job! (4 suppressed)
```
> The suppressed findings are expected permission blocks at the top-level of a workflow, but we set this for each job.
> ci: pin actions workflow step hashes and use minimum permissions

- tests/slack_sdk_async/socket_mode/test_aiohttp.py
`tests/slack_sdk_async/socket_mode/test_aiohttp.py:test_init_with_loop` was broken by `aiohttp` [version 3.12.6](https://github.com/aio-libs/aiohttp/releases/tag/v3.12.6) with the following error
```txt
RuntimeError: Session and connector has to use same event loop
env_3.13.1/lib/python3.13/site-packages/aiohttp/client.py:368: RuntimeError
```
The test aims to validate that a `loop` can be passed to the `SocketModeClient`, previously a new loop was created and passed to the `SocketModeClient` constructor, this PR changes this behavior by passing the existing loop related to the unit tests.
N/A
> fix: aiohttp test_init_with_loop broken test

- .github/dependabot.yml
- scripts/build_pypi_package.sh
- scripts/deploy_to_prod_pypi_org.sh
- scripts/deploy_to_test_pypi_org.sh
- scripts/generate_api_docs.sh
- scripts/run_integration_tests.sh
- scripts/run_mypy.sh
- scripts/run_unit_tests.sh
- scripts/run_validation.sh
- slack_sdk/oauth/installation_store/internals.py
- slack_sdk/scim/v1/internal_utils.py
- tests/slack_sdk/oauth/installation_store/test_internals.py
These are minor changes that clean up the project based on python 3.6 support drop in #1735
The CI should cover the testing
> chore: clean up project based on 3.6 removal

- docs/reference/index.html
- docs/reference/oauth/installation_store/file/index.html
- docs/reference/oauth/installation_store/index.html
- docs/reference/oauth/state_store/file/index.html
- docs/reference/oauth/state_store/index.html
- docs/reference/web/async_client.html
- docs/reference/web/client.html
- docs/reference/web/index.html
- docs/reference/web/legacy_client.html
- slack_sdk/web/async_client.py
- slack_sdk/web/client.py
- slack_sdk/web/legacy_client.py
- tests/slack_sdk_async/web/test_web_client_coverage.py
This pull request updates the `chat_startStream` method to require the `thread_ts` argument.
I've categorized this as a fix, since the Slack API has been updated to now require `thread_ts` when starting a conversation stream.
We'll want to update our AI Sample app to also require `thread_ts` once this is merged.
> fix(web-client): update `thread_ts` to be required for `chat_startStream`

- docs/reference/index.html
- docs/reference/web/async_client.html
- docs/reference/web/client.html
- docs/reference/web/index.html
- docs/reference/web/legacy_client.html
- slack_sdk/web/async_client.py
- slack_sdk/web/client.py
- slack_sdk/web/legacy_client.py
- tests/slack_sdk_async/web/test_web_client_coverage.py
This PR uses the JSON content type to send structured values, such as an array of `loading_messages` to the server with correct encodings 🤖 
Test cases now include arguments that require this `json` content type!
> fix(web): send structured values to "assistant.threads.setStatus" method using json content type

- docs/reference/index.html
- docs/reference/web/async_client.html
- docs/reference/web/client.html
- docs/reference/web/index.html
- docs/reference/web/legacy_client.html
- slack_sdk/web/async_client.py
- slack_sdk/web/client.py
- slack_sdk/web/legacy_client.py
This PR removes `unfurl_links` and `unfurl_media` arguments from the "chat.startStream" method to align with the backend.
Calls without these arguments should continue to succeed.
> fix(web-api): remove unfurl arguments from chat.startStream method

- docs/english/web.md
> docs: fixes formatting error for ai apps docs
