slackapi/python-slack-sdk

README.md

Now using: https://api.slack.com/web#authentication

Update token generation url

---

setup.py
slackclient/_server.py
slackclient/_slackrequest.py

This solved SSL certificate verification failure issue, caused by urllib.request implementation

Moved from urllib to requests

---

README.md

Improvement to the formatting of methods in README.md.

Move method calls to a table in README.md

---

README.md

Having a basic example of how to post a message would be very useful, IMHO. That's what most people are trying to do initially, I'd guess.

add post message example to the README

---

doc/examples/example.py

Added doc/example/example.py

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md

> Fixing copy paste error
> N/A
> N/A

Fixing copy/paste error in github templates

---

README.md

Adds a version badge to the Readme making it easier to find the package on PyPi
No related issues
Manual verification: [check the readme on my branch](https://github.com/hockeybuggy/python-slackclient/tree/add-a-version-badge)
It looks like this:

Add a version badge to the Readme that links the PyPi.

---

slackclient/_server.py

> This is not referenced or used anywhere else in the code. So I removed it.

Removing unused pingcounter

---

docs-src/index.rst
docs/index.html

Fixed dev4slack link
* ✅ I've read and understood the [Contributing guidelines](https://github.com/slackapi/python-slackclient/blob/master/.github/CONTRIBUTING.md) and have done my best effort to follow them.
* ✅ I've read and agree to the [Code of Conduct](https://github.com/slackapi/python-slackclient/blob/master/CODE_OF_CONDUCT.md).
* ✅ I've been mindful about doing atomic commits, adding documentation to my changes, not refactoring too much.
* ✅ I've a descriptive title and added any useful information for the reviewer. Where appropriate, I've attached a screenshot and/or screencast (gif preferably).
* ⬜️  I've written tests to cover the new code and functionality included in this PR.
* ✅ I've read, agree to, and signed the [Contributor License Agreement (CLA)]

Fixed dev4slack link

---

docs-src/auth.rst

fix small typo in Auth document

fix typo about token access in auth.rst

---

.travis.yml
tox.ini

> e.g. New functionality for producing whatsits.
> e.g. Fixes #206 and closes #230
> e.g. Add tests around whatsit production.

Add Python 3.6 to testing

---

.gitignore
slackclient/_client.py
slackclient/_server.py
slackclient/_slackrequest.py
tests/test_slackclient.py

Allow use for proxies when creating websockets and calling slack apis.
This PR didn't change the user end docs, just the API docs, which I don't think is being shown anywhere on [the docs](https://api.slack.com/), but the [FAQ](http://slackapi.github.io/python-slackclient/faq.html#how-do-i-compile-the-documentation) says I have to re-compile the docs if I added any docs. I'll revert the docs change or put them in a separate commit if in need.
None
I'm not sure how to test this feature.
I'm using `python-slackclient` in China so I'm very interested in proxy functionalities in slack client, there's a [old PR](https://github.com/slackapi/python-slackclient/pull/68) solving the same problem but I don't think @pfrederiks have time to continue the work, so I copied a few lines of code and …

allow use for proxy

---

README.rst

move to the slackapi owned appveyor project (from aoberoi owned)

---

slackclient/server.py
slackclient/user.py
tests/test_server.py

include email as user property

---

slackclient/client.py
slackclient/server.py

Fix Build Error

---

test_requirements.txt

pin pytest to supported python versions

---

docs-src/_themes/slack/layout.html
docs/_static/basic.css
docs/_static/doctools.js
docs/_static/searchtools.js
docs/about.html
docs/auth.html
docs/basic_usage.html
docs/changelog.html
docs/conversations.html
docs/faq.html
docs/genindex.html
docs/index.html
docs/metadata.html
docs/real_time_messaging.html
docs/search.html

Added GA code to docs pages

---

docs-src/changelog.rst
docs/about.html
docs/auth.html
docs/basic_usage.html
docs/changelog.html
docs/conversations.html
docs/faq.html
docs/genindex.html
docs/index.html
docs/metadata.html
docs/real_time_messaging.html
docs/search.html

- Setting the correct date for the 1.1.0 release date
- Formatting past release versions to same standard
* [ x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/python-slackclient/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

Updating changelog versions

---

slackclient/slackrequest.py

Fixed JSON encoding for Web API request params

Fixed JSON encoding for Web API request params

---

slackclient/server.py

Fix build errors

---

docs-src/faq.rst

Remove obsolete missing RTM API support from FAQ

---

slack/rtm/client.py
slack/web/client.py
slack/web/slack_response.py

Sample code for the in code comments don't include `import os`

Modified to the comments to include `import os` for clarification

---

README.md
documentation_v2/Migration.md
documentation_v2/auth.md
documentation_v2/basic_usage.md

Includes the docmentation, basic usage, auth and migration guide for the v2 of the client. Rebuilt branch to clean it up.

Documentation for v2 client

---

slack/version.py

Bumping the version so we can redistribute the package without the deprecated files.

Bumping version 

---

slack/web/client.py

Updated to include the Scheduled Messages API, removed deprecated `files.comments.add` endpoint

added scheduled messages api, removed file_command_add api endpoint

---

documentation_v2/basic_usage.md

Changed `auth` redirection to the correct page

---

slack/web/client.py

fix the broken argument names in `channels.*`

---

slack/rtm/client.py

In #420 , we fixed this in the Readme files, we didn't fix it in the code comment. This should finalize it

modified comment to include the correct arg for the rtm client files

---

documentation_v2/examples/asyncio.md

Hi, I wanted to use a new `WebClient` with `asyncio` but I took me some time to understand.
So I created this minimal example on how to send DM to all users from some channel.
Let me know if you'd like to have it in docs for v2. And I can add a bit more information to the page.

[WIP/Proposal] Add async client example [docs]

---

slackclient/server.py

Ensuring that reconnects use rtm.start

---

slack/web/client.py

The updated methods for Schedule Message and Scheduled Messages List were incorrectly cased in #428 . This fixes and resolves a breaking change

The methods were incorrectly cased and would fail

---

.deepsource.toml
slack/web/base_client.py

Hi! It was great meeting the team at the booth in PyCon this morning!
I've added a customized `.deepsource.toml` as part of the PR that you can start using directly to run DeepSource analysis. I've also fixed some issues flagged by our analyzers while I was at it 😄
To continue running analysis on every PR, just follow these simple steps:
1. **Merge this PR.**
2. **Sign up on DeepSource** and grant access to this repository [here](https://deepsource.io/signup/).
3. **Activate analysis on this repo** [here](http://deepsource.io/gh/mongodb/mongo-python-driver).
Tip: You can also take a look at the [docs](https://deepsource.io/docs/guides/quickstart.html).
Please let me know if you have any questions! :)

Fix some quality issues, add .deepsource.toml file

---

README.md

PR is meant to add more documentation in the README around the usage of async.
Examples and some description of the usage of asyncio/aiohttp ability of slackClient v2.

Update docs for async functionality

---

slack/web/base_client.py

Fixes #431
Not sure if tests are necessary for this? It's not really _doing_ anything, you just have to make sure you pass the fields into it correctly.

Signature verification staticmethod on base client

---

slack/rtm/client.py

Fixes #451 
Happy to have a discussion on the right solution for this. It works as-is but I expect there's something I haven't thought of. I'm on the #sdk-python-slack channel if you want to talk in real time.

Handle case in which aiohttp closes the websocket due to lack of ping responses.

---

setup.py

Simple change to fix our PyPi page.

Updating setup.py to include the long description type

---

README.md
slack/rtm/client.py
tutorial/03-responding-to-slack-events.md
tutorial/PythOnBoardingBot/app.py
tutorial/PythOnBoardingBot/async_app.py

When following along the tutorial I noticed a typo that I wanted to fix (recieved -> received).

Fix typo; recieved -> received

---

docs-src/index.rst

HT to ekinsey :)
Just fixin' a typo

Fix missing word and typo

---

slack/web/client.py

Adding required 'view' param

---

docs-src/changelog.rst
docs/changelog.html

Referenced the wrong API method.

Fixing typo

---

docs-src/index.rst
docs/index.html

Fix Slack Community link

---

slack/web/client.py

Added oAuth.v2.access API

---

slack/web/client.py

Added `admin.users.setExpiration` and `admin.users.list` api methods. 
Issue: #591

Added admin.users.setExpiration and admin.users.list api methods

---

docs-src/real_time_messaging.rst
docs/.buildinfo
docs/real_time_messaging.html

The code snippet demonstrating RTM usage gets an error when posting a reply in the message's thread.
```
ERROR:slack.rtm.client:When calling '#say_hello()' in the '__main__' module the following error was raised: 'text'
File "app.py", line 27, in <module>
rtm_client.start()
File "/path-to-python/lib/python3.8/site-packages/slack/rtm/client.py", line 198, in start
return self._event_loop.run_until_complete(future)
File "/path-to-python/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
return future.result()
File "/path-to-python/lib/python3.8/site-packages/slack/rtm/client.py", line 339, in _connect_and_read
await self._read_messages()
File "/path-to-python/lib/python3.8/site-packages/slack/rtm/client.py", line 390, in _read_messages …
```

Fix a code snippet in RTM document

---

docs-src/basic_usage.rst

This pull request fixes #640 by updating the code snippet demonstrating how to deal with rate_limited errors.
I haven't run `./docs.sh` yet. After merging #646, I will run it and merge this PR.

#640 Update the rate_limited error handling code snippet

---

.gitignore
docs-src/real_time_messaging.rst

This pull request applies a minor improvement to the RTM document. Such a clearer guide would be helpful particularly for Slack app development beginners. This fixes #503 .

Fix #503 improve the document to be clearer about embedding user ID

---

tutorial/01-creating-the-slack-app.md

This pull request fixes #655 by updating the page to be up-to-date (with granular permissions).

Fix #655 Tutorial documentation: "im:write" scope needed

---

.travis.yml

Travis CI: The sudo tag has been deprecated and removed from Travis docs

---

slack/rtm/client.py

#665 had a dependency on #662 but the fix can be independent. This pull request brings the only necessary changes for fixing #661 
This pull request fixes https://github.com/slackapi/python-slackclient/issues/611 by stopping the propagation of user exceptions to `_connect_and_read()` method. Raised exceptions to `_connect_and_read()` results in WebSocket connection closure. That is not intended in the scenarios where developers don't handle (or forget handling) exceptions in their methods decorated by `@RTMClient.run_on`.
You can verify the validity of this change by running an integration test: https://github.com/slackapi/python-slackclient/blob/master/integration_tests/rtm/test_issue_611.py

Fix #611 - stop propagating user exceptions to the connection management layer

---

tutorial/03-responding-to-slack-events.md

the wrong word was fixed  from "Add the the following line under the previous code" to "Add the following line under the previous code"

Fix a typo in 03-responding-to-slack-events.md

---

slack/web/classes/blocks.py
slack/web/classes/objects.py
tests/web/classes/test_blocks.py

Fix "InputBlock" hint validation

---

tutorial/PythOnBoardingBot/app.py

Change 'reaction_added' event to 'pin_added' event in the comment, in line 97 for Pin Added Events.

Update comment in app.py

---

integration_tests/web/test_admin_usergroups.py
integration_tests/web/test_calls.py
slack/web/client.py
tests/web/test_web_client_coverage.py

This pull request fixes #757 by adding missing two endpoints to `WebClient`.

Add admin.usergroups.addTeams, calls.participants.remove API #757

---

.deepsource.toml
slack/errors.py
slack/rtm/client.py
slack/signature/verifier.py
slack/web/base_client.py
slack/web/classes/__init__.py
slack/web/classes/actions.py
slack/web/classes/attachments.py
slack/web/classes/blocks.py
slack/web/classes/dialog_elements.py
slack/web/classes/dialogs.py
slack/web/classes/elements.py
slack/web/classes/interactions.py
slack/web/classes/messages.py
slack/web/classes/objects.py
slack/web/classes/views.py
slack/web/client.py
slack/web/slack_response.py
slack/webhook/client.py

This pull request adjusts this project's DeepSource configuration.
The current configuration detects so many minor issues in tests and integration_tests that it's a bit hard to check only the essential issues. The changes in this PR mitigates the issues for the project maintainers.
~~Also, I wanted to check if how mypy works in DeepSource. If it seems really useful, I'd like to introduce the setting this time. If it's not relevant to this project, I'll revert the change before merging this PR.~~ **EDIT**: I decided to hold off enabling mypy this time as some are false detections.

Adjust DeepSource configuration

---

.github/ISSUE_TEMPLATE/02_enhancement.md
.github/ISSUE_TEMPLATE/03_document.md
.github/pull_request_template.md
README.md

This pull request updates GitHub templates and README for v3 #806

[v3] Update GitHub templates and README

---

integration_tests/samples/oauth/oauth_v2_legacy.py
setup.py
slack_sdk/oauth/__init__.py
slack_sdk/oauth/authorize_url_generator/__init__.py
slack_sdk/oauth/installation_store/__init__.py
slack_sdk/oauth/installation_store/amazon_s3/__init__.py
slack_sdk/oauth/installation_store/async_installation_store.py
slack_sdk/oauth/installation_store/file/__init__.py
slack_sdk/oauth/installation_store/installation_store.py
slack_sdk/oauth/installation_store/models/__init__.py
slack_sdk/oauth/installation_store/models/bot.py
slack_sdk/oauth/installation_store/models/installation.py
slack_sdk/oauth/installation_store/sqlite3/__init__.py
slack_sdk/oauth/redirect_uri_page_renderer/__init__.py
slack_sdk/oauth/state_store/__init__.py
slack_sdk/oauth/state_store/amazon_s3/__init__.py
slack_sdk/oauth/state_store/async_state_store.py
slack_sdk/oauth/state_store/file/__init__.py
slack_sdk/oauth/state_store/sqlite3/__init__.py
slack_sdk/oauth/state_store/state_store.py
slack_sdk/oauth/state_utils/__init__.py
tests/slack_sdk_tests/oauth/authorize_url_generator/test_generator.py
tests/slack_sdk_tests/oauth/installation_store/test_file.py
tests/slack_sdk_tests/oauth/installation_store/test_interaface.py
tests/slack_sdk_tests/oauth/installation_store/test_sqlite3.py
tests/slack_sdk_tests/oauth/redirect_uri_page_renderer/test_init.py
tests/slack_sdk_tests/oauth/state_store/test_file.py
tests/slack_sdk_tests/oauth/state_store/test_sqlite3.py
tests/slack_sdk_tests/oauth/state_utils/test_utils.py
tests/slack_sdk_tests/oauth/test_init.py

This pull request adds OAuth module to slack-sdk v3. ref #806

[v3] Add OAuth module

---

docs-src/_themes/slack/sidebar.html
docs-src/metadata.rst
docs/about.html
docs/auth.html
docs/basic_usage.html
docs/changelog.html
docs/conversations.html
docs/faq.html
docs/genindex.html
docs/index.html
docs/metadata.html
docs/real_time_messaging.html
docs/search.html

(Describe the goal of this PR. Mention any related Issue numbers)

Replace master branch with main in docs

---

slack/web/base_client.py
slack/webhook/client.py
slack_sdk/web/base_client.py
slack_sdk/web/legacy_base_client.py
tests/slack_sdk/web/mock_web_api_server.py
tests/slack_sdk/web/test_web_client_issue_829.py
tests/slack_sdk/webhook/mock_web_api_server.py
tests/slack_sdk/webhook/test_webhook.py
tests/slack_sdk_async/web/test_async_web_client.py
tests/slack_sdk_async/web/test_web_client_issue_829.py
tests/web/mock_web_api_server.py
tests/web/test_async_web_client.py
tests/web/test_web_client.py
tests/webhook/mock_web_api_server.py
tests/webhook/test_webhook.py

This pull request brings the improvements by #833 to the `v3` branch.

Pick #833 for v3 branch

---

tutorial/03-responding-to-slack-events.md
tutorial/PythOnBoardingBot/app.py
tutorial/PythOnBoardingBot/async_app.py
tutorial/PythOnBoardingBot/onboarding_tutorial.py
tutorial/PythOnBoardingBot/requirements.txt
tutorial/README.md

This pull request updates the tutorial content in this repository, as part of #806.

[v3] Update the tutorial to be up-to-date with v3

---

slack_sdk/web/async_client.py
slack_sdk/web/client.py

Fixed view_* methods to allow using View model

---

.travis.yml

(Describe the goal of this PR. Mention any related Issue numbers)

Travis CI: Add Python 3.9 to the testing

---

slack_sdk/version.py

This pull request starts the release operations for v3.0.0rc2.
```bash
./scripts/run_unit_tests.sh 
./scripts/run_integration_tests.sh
python setup.py upload
git checkout main
git merge v3.0.0rc2-release
git push slackapi main
git push slackapi --tag v3.0.0rc2
```
Milestone: https://github.com/slackapi/python-slack-sdk/milestone/10

version 3.0.0rc2

---

slack_sdk/oauth/installation_store/amazon_s3/__init__.py
slack_sdk/oauth/installation_store/async_cacheable_installation_store.py
slack_sdk/oauth/installation_store/async_installation_store.py
slack_sdk/oauth/installation_store/cacheable_installation_store.py
slack_sdk/oauth/installation_store/file/__init__.py
slack_sdk/oauth/installation_store/installation_store.py
slack_sdk/oauth/installation_store/models/bot.py
slack_sdk/oauth/installation_store/models/installation.py
slack_sdk/oauth/installation_store/sqlalchemy/__init__.py
slack_sdk/oauth/installation_store/sqlite3/__init__.py
tests/slack_sdk/oauth/installation_store/test_file.py
tests/slack_sdk/oauth/installation_store/test_sqlalchemy.py
tests/slack_sdk/oauth/installation_store/test_sqlite3.py

This pull request adds the complete support for org-level app installation feature branch by @stevengill - I will add review comments for details.

to: feat-org-apps - Add find_installation support in #877

---

slack_sdk/rtm/v2/__init__.py
slack_sdk/socket_mode/async_client.py
slack_sdk/socket_mode/builtin/client.py
slack_sdk/socket_mode/builtin/connection.py
slack_sdk/socket_mode/builtin/internals.py
slack_sdk/socket_mode/client.py
tests/rtm/test_rtm_client_v2.py

This pull request resolves #960 by adding error handling code.
Also, some changes in this PR eliminates the issues described at #959. As I'm not 100% confident that this PR can completely resolve #959, I won't close the issue by merging this PR.

Fix #960 rtm.connect API rate-limited error handling & improvements for #959

---

setup.py

[#1027] Update websockets package version requirements

---

.github/maintainers_guide.md

Updates with command to run `integration_tests` based on `setup.py` line 319.

Update command in maintainers guide

---

docs/assets/basic.css
docs/assets/classic.css
docs/assets/doctools.js
docs/assets/language_data.js
docs/assets/searchtools.js
docs/assets/sidebar.js
docs/oauth/index.html
slack_sdk/version.py

Getting ready for a new release!

version 3.15.0

---

slack_sdk/oauth/installation_store/amazon_s3/__init__.py
slack_sdk/oauth/installation_store/file/__init__.py
slack_sdk/oauth/installation_store/sqlalchemy/__init__.py
slack_sdk/oauth/installation_store/sqlite3/__init__.py

This pull request resolves the issue described at https://github.com/slackapi/bolt-python/issues/664 for the built-in installation stores. Refer to the issue for the details.

Improve the installation data queries to always return the latest bot token

---

scripts/uninstall_all.sh

Improve the robustness of the uninstall script
Install a variety of packages and then use the uninstall script to clean things up

chore: increase the robustness of the uninstall script
